<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mehmet Göktuğ ÖZTÜRK">
<meta name="dcterms.date" content="2025-12-15">
<meta name="description" content="Base R ile Veri Cambazlığı">

<title>PENGUINS VERİSİ İLE BASE R’A GİRİŞ – R DELİSİ</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<link href="../../favicon.jpeg" rel="icon" type="image/jpeg">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-49b5fa840c0f1a9482e326475defaf18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&amp;family=Atkinson+Hyperlegible+Mono:wght@400;700&amp;display=swap">


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="PENGUINS VERİSİ İLE BASE R’A GİRİŞ – R DELİSİ">
<meta property="og:description" content="Base R ile Veri Cambazlığı">
<meta property="og:image" content="figs/penguins.webp">
<meta property="og:site_name" content="R DELİSİ">
<meta name="twitter:title" content="PENGUINS VERİSİ İLE BASE R’A GİRİŞ – R DELİSİ">
<meta name="twitter:description" content="Base R ile Veri Cambazlığı">
<meta name="twitter:image" content="figs/penguins.webp">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">R DELİSİ</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">BLOG</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">HAKKIMDA</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://ecoevo.social/@mehmet_goktu"> <i class="bi bi-mastodon" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mehmetgoktug"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mehmetgoktug/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PENGUINS VERİSİ İLE BASE R’A GİRİŞ</h1>
  <div class="quarto-categories">
    <div class="quarto-category">R</div>
    <div class="quarto-category">base R</div>
    <div class="quarto-category">palmerpenguins</div>
  </div>
  </div>

<div>
  <div class="description">
    Base R ile Veri Cambazlığı
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mehmet Göktuğ ÖZTÜRK </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/penguins.webp" class="img-fluid figure-img"></p>
<figcaption>Kaynak: <a href="https://allisonhorst.github.io/palmerpenguins/articles/art.html">Allison Horst</a></figcaption>
</figure>
</div>
<p><strong>Merhabalar, blogun yeni yazısına hoş geldiniz.</strong> <strong>Takıldığınız ve anlamadığınız yerler olursa lütfen yorum yapmaya çekinmeyiniz.</strong> <strong>Ayrıca katkılarınızı ve eleştirilerinizi de bekliyorum. Keyifli okumalar.</strong></p>
<p>Bu yazıda, R’da son yılların en sevilen veri setlerinden birisini kullanarak birçok temel işi yapmayı, yeni başlayanlar için yol gösterici, yardımcı bir rehber oluşturmayı hedefliyorum. R öğrenmeye yeni başlayan arkadaşım Rüveyda ile R çalışırken, bu gibi bir yazının yeni başlayanlar için oldukça faydalı olabileceğini düşündüm ve bu yazıyı yazmaya karar verdim. Önceki yazıların aksine ulaşılması daha kolay olan bir veri seti üzerinden çalışacağımız için, yazıyı okurken bir yandan da alıştırma yapmak daha kolay olacaktır. Bol bol alıştırma yapmanızı öneriyorum. Bazı yerlerde biraz ayrıntıya girmiş olabilirim, bu sizi korkutmasın, motivasyonunuzu kırmasın. Yalnızca devam edin ve diğer kısımlara bakın, sonra geri dönüp takıldığınız yerlere bakabilirsiniz.</p>
<p>“Palmer Penguins” veri seti, son dönemde veri bilimi ve istatistik alanında en çok kullanılan eğitim-uygulama veri setlerinden birisi. Öncelikle <a href="https://allisonhorst.github.io/palmerpenguins/index.html">palmerpenguins</a> paketi yayımlanmış, gördüğü ilginin ardından da bu veri seti, R 4.5.0 sürümüyle beraber R’ı yüklediğimiz zaman varsayılan olarak (base R ile) gelen <code>{datasets}</code> paketine dahil edilmiştir. Veriyi daha iyi tanımak ve yapılan örnek çalışmaları görmek için <a href="https://allisonhorst.github.io/palmerpenguins/index.html">şu siteyi</a> mutlaka incelemenizi öneririm.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/penguins3.webp" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Kaynak: <a href="https://allisonhorst.github.io/palmerpenguins/articles/art.html">Allison Horst</a></figcaption>
</figure>
</div>
<section id="giriş" class="level2">
<h2 class="anchored" data-anchor-id="giriş">1. GİRİŞ</h2>
<p>Bugün bu veri setini kullanarak R’daki birçok temel analizi yapacağız. Bu yazıda yalnızca <code>base R</code> (R programlama dilini yüklediğimiz zaman varsayılan olarak gelen paketler) kullanacağız. Hiçbir paket yüklemeye gerek kalmadan, <code>palmerpenguins</code> verisini inceleyecek, veriyle oynayacak ve basit grafikler çizeceğiz. Buradaki amacım bir data.frame üzerinde çalışırken <code>base R</code>’a dair birçok temel noktayı ele alabilmek. Dolayısıyla göreceğimiz fonksiyonların hepsini, bir veriyi analiz ederken mutlaka kullanmanız gerekmiyor. Yalnızca o an gerekenleri, işinize yarayanları kullanmanız yeterli olacaktır.<br>
Bir sonraki yazıda <code>dplyr</code> ve <code>ggplot2</code> versiyonunu göreceğiz. :)</p>
<p>Henüz başlamamışken şu iki harika base R kılavuzunu buraya bırakayım:</p>
<ol type="1">
<li><a href="https://rspatial.org/intr/index.html">Introduction to R</a></li>
<li><a href="https://github.com/matloff/fasteR">fasteR: Fast Lane to Learning R!</a></li>
</ol>
<p>Şimdi <code>penguins</code> verisine bakalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>penguins</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species    island bill_len bill_dep flipper_len body_mass    sex year
1   Adelie Torgersen     39.1     18.7         181      3750   male 2007
2   Adelie Torgersen     39.5     17.4         186      3800 female 2007
3   Adelie Torgersen     40.3     18.0         195      3250 female 2007
4   Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5   Adelie Torgersen     36.7     19.3         193      3450 female 2007
6   Adelie Torgersen     39.3     20.6         190      3650   male 2007
7   Adelie Torgersen     38.9     17.8         181      3625 female 2007
8   Adelie Torgersen     39.2     19.6         195      4675   male 2007
9   Adelie Torgersen     34.1     18.1         193      3475   &lt;NA&gt; 2007
10  Adelie Torgersen     42.0     20.2         190      4250   &lt;NA&gt; 2007
11  Adelie Torgersen     37.8     17.1         186      3300   &lt;NA&gt; 2007
12  Adelie Torgersen     37.8     17.3         180      3700   &lt;NA&gt; 2007
13  Adelie Torgersen     41.1     17.6         182      3200 female 2007
14  Adelie Torgersen     38.6     21.2         191      3800   male 2007
15  Adelie Torgersen     34.6     21.1         198      4400   male 2007
16  Adelie Torgersen     36.6     17.8         185      3700 female 2007
17  Adelie Torgersen     38.7     19.0         195      3450 female 2007
18  Adelie Torgersen     42.5     20.7         197      4500   male 2007
19  Adelie Torgersen     34.4     18.4         184      3325 female 2007
20  Adelie Torgersen     46.0     21.5         194      4200   male 2007
21  Adelie    Biscoe     37.8     18.3         174      3400 female 2007
22  Adelie    Biscoe     37.7     18.7         180      3600   male 2007
23  Adelie    Biscoe     35.9     19.2         189      3800 female 2007
24  Adelie    Biscoe     38.2     18.1         185      3950   male 2007
25  Adelie    Biscoe     38.8     17.2         180      3800   male 2007
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p>Gördüğünüz gibi birçok satır ve sütundan oluşan bir veri tablosu. Öncesinde R konsolunun kaç tane değer yazdıracağını ayarlamadıysanız veriyi bu şekilde çağırmak, tüm veri tablosunu konsola yazdıracaktır. Bu durum, büyük veri tablolarında istenmeyen bir durum. Bundan kaçınmak için <code>head()</code> ve <code>tail()</code> fonksiyonlarını kullanabilir, verinin ilk 6 ve son 6 satırını görüntüleyebilirsiniz ancak öncelikle bir verimizin yapısını tanıyalım, sonrasında bu fonksiyonları kullanarak verinin bir alt kümesini görüntüleyelim.</p>
<p>Bu veri tablosunun hangi sınıfta yer aldığını, hangi veri yapısına sahip olduğunu görmek için <code>class()</code> fonksiyonunu kullanabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>Gördüğünüz gibi bir <code>data.frame</code>. Yani satır (gözlem) ve sütunlardan (değişken) oluşan, tıpkı bir Excel tablosu gibi olan bir veri tablosu.</p>
<p>Şimdi de verinin yapısına daha ayrıntılı bakmak için <code>str()</code> fonksiyonunu kullanalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  8 variables:
 $ species    : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island     : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_len   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_dep   : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_len: int  181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass  : int  3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex        : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year       : int  2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
</div>
</div>
<p>Gördüğünüz gibi 344 gözlem ve 8 değişkenden oluşan bir veri tablosu. Verideki 1. (species) 2. (island) ve 3. (sex) değişken kategorik değişkenler için kullandığımız <code>factor</code> veri tipindeyken, 3. (bill_len) ve 4. değişken (bill_dep) numeric (double) ve 5. (flipper_len), 6. (body_mass) ve 8. (year) değişken integer veri tipinde. Double - numeric veri tipini, kompleks sayılar dışında kalan tüm sayılar için kullanabiliriz. Tam sayılar dışındaki sayılar için genellikle daha kullanışlı. Integer ise ismiyle müsemma tam sayılar için kullanılan bir veri tipi.</p>
<p>Başta karmaşık gelebilir ancak zamanla, alıştırma yaptıkça size çok doğal, çok kolay gelmeye başlayacak.</p>
<p>Data frame’ler, gördüğünüz gibi birbirinden farklı veri tipindeki değişkenleri tutabiliyor. Bu özelliğiyle içerisinde her şeyi tutabildiğimiz <code>list()</code> veri yapısında oldukça benziyor. Zaten 2 boyutlu yapısıyla matrix’lere benzese de data.frame’ler asıl olarak birer list’tir. Onu, matrix’lere benzeyen list’ler gibi düşünebilirsiniz. Bu yapısıyla matrix’ler gibi dikdörtgen şeklinde, düzenli bir şekilde veri tutabiliyor ama aynı zamanda list’ler gibi de oldukça esnek bir yapısı var. Veri analizinde kullanılmak için daha uygun veri yapıları.</p>
<p>Yine kafanız karışmış olabilir. Zamanla oturacak, merak etmeyin. Benim data.frame’lerin birer list olduğunu fark etmem oldukça uzun bir zaman aldı mesela. Ne kadar erken öğrenirseniz işlerinizi o kadar etkili yapabilirsiniz.</p>
<p>Şimdi verimizin ilk ve son 6 satırına bakabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_len bill_dep flipper_len body_mass    sex year
1  Adelie Torgersen     39.1     18.7         181      3750   male 2007
2  Adelie Torgersen     39.5     17.4         186      3800 female 2007
3  Adelie Torgersen     40.3     18.0         195      3250 female 2007
4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5  Adelie Torgersen     36.7     19.3         193      3450 female 2007
6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
339 Chinstrap  Dream     45.7     17.0         195      3650 female 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
341 Chinstrap  Dream     43.5     18.1         202      3400 female 2009
342 Chinstrap  Dream     49.6     18.2         193      3775   male 2009
343 Chinstrap  Dream     50.8     19.0         210      4100   male 2009
344 Chinstrap  Dream     50.2     18.7         198      3775 female 2009</code></pre>
</div>
</div>
<p><code>?head</code> ya da <code>help(head)</code> fonksiyonlarını çalıştırarak dokümantasyonuna ulaşabilirsiniz. Burada bu fonksiyonların nasıl çalıştığı ve hangi argümanları alabileceği konusunda ayrıntılı bilgiye ulaşabilirsiniz. R’a ilk başlayanlar için dokümantasyonlar karmaşık gelebilir. Öncelikle anlamaya çalışın, eğer zorlanırsanız da Google kullanarak herhangi bir fonksiyon hakkında oldukça basit ve kullanışlı kaynaklara erişebilirsiniz. Birçok iyi yazılımcı ve R kullanıcısı, çok basit işlevleri bile unutup Google’den yardım alabiliyor. Hata yapmaktan ve yardım almaktan asla çekinmeyin. Hata yapmıyorsanız bir programlama dilini öğrenmiyorsunuz demektir. Tabi artık Google yerine ChatGPT gibi yapay dil modellerinden de faydalanabilirsiniz ama öğrenmenin ilk aşamalarında pek önermem.</p>
<p>Şimdi dokümantasyonda gördüğünüz <code>n</code> argümanını kullanarak kaç adet satır görüntülemek istediğinizi seçebilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(penguins, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species    island bill_len bill_dep flipper_len body_mass    sex year
1   Adelie Torgersen     39.1     18.7         181      3750   male 2007
2   Adelie Torgersen     39.5     17.4         186      3800 female 2007
3   Adelie Torgersen     40.3     18.0         195      3250 female 2007
4   Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5   Adelie Torgersen     36.7     19.3         193      3450 female 2007
6   Adelie Torgersen     39.3     20.6         190      3650   male 2007
7   Adelie Torgersen     38.9     17.8         181      3625 female 2007
8   Adelie Torgersen     39.2     19.6         195      4675   male 2007
9   Adelie Torgersen     34.1     18.1         193      3475   &lt;NA&gt; 2007
10  Adelie Torgersen     42.0     20.2         190      4250   &lt;NA&gt; 2007</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(penguins, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
335 Chinstrap  Dream     50.2     18.8         202      3800   male 2009
336 Chinstrap  Dream     45.6     19.4         194      3525 female 2009
337 Chinstrap  Dream     51.9     19.5         206      3950   male 2009
338 Chinstrap  Dream     46.8     16.5         189      3650 female 2009
339 Chinstrap  Dream     45.7     17.0         195      3650 female 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
341 Chinstrap  Dream     43.5     18.1         202      3400 female 2009
342 Chinstrap  Dream     49.6     18.2         193      3775   male 2009
343 Chinstrap  Dream     50.8     19.0         210      4100   male 2009
344 Chinstrap  Dream     50.2     18.7         198      3775 female 2009</code></pre>
</div>
</div>
<p>Gördüğünüz gibi ilk ve son 10 satırı görebildik. <code>n</code> argümanının ikinci argüman olması dolayısıyla bu fonksiyonları doğrudan, <code>head(penguins, 10)</code> şeklinde de kullanabilirsiniz.</p>
<p>Benzer bir işlemi kare parantez, yani indeksleme (slicing), kullanarak da yapabiliriz. Burada, görüntülemek istediğimiz satır ve sütunları manuel olarak seçeceğiz. Virgülden önceki değer her zaman ilk boyutu, yani satırları; sonraki değer ise ikinci boyutu, yani sütunları seçmek için kullanılıyor.</p>
<p><code>str()</code> fonksiyonuyla zaten bilgi edinmiştik ama tekrardan verimizin uzunluğuna, boyutlarına bir bakalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>Vektörlerin uzunluğunu öğrenmek için kullandığımız <code>length()</code> fonksiyonu bize data.frame hakkında yeterince bilgi vermedi. Eğer bir vektör ya da matrix ile çalışsaydık tüm elemanların sayısını öğrenebilirdik ama data.frame bize yalnızca sütun (değişken) sayısını verdi. Neden? Çünkü biraz önce de belirttiğim gibi data.frame’ler özünde sütunlardan - vektörlerden oluşan birer list’tir! Ama aynı zamanda da matrix gibi 2 boyutlu bir veridir. Dolayısıyla <code>dim()</code> fonksiyonuyla tıpkı matrix’lerde olduğu gibi verinin boyutlarına ulaşabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 344   8</code></pre>
</div>
</div>
<p>Gördüğünüz gibi verimiz 344 satır (gözlem) ve 8 sütundan (değişken) oluşuyor.</p>
<p><code>head()</code> fonksiyonunun yaptığı gibi ilk altı satırı görmek istediğimizi düşünelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_len bill_dep flipper_len body_mass    sex year
1  Adelie Torgersen     39.1     18.7         181      3750   male 2007
2  Adelie Torgersen     39.5     17.4         186      3800 female 2007
3  Adelie Torgersen     40.3     18.0         195      3250 female 2007
4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5  Adelie Torgersen     36.7     19.3         193      3450 female 2007
6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</code></pre>
</div>
</div>
<p>Burada <code>1:6</code> ifadesi, 1’den 6’ya kadar sayılar üret demenin kolay yolu. <code>seq()</code> fonksiyonunun basitleştirilmiş hâli olarak düşünebilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5 6</code></pre>
</div>
</div>
<p>Bakın 1’den 6’ya kadar olan sayılara bir vektör olarak eriştik. Bunu, yukarıdaki örnekteki gibi bir data.frame’in ilk 6 satırını görmek için kullanabiliriz.</p>
<p>Aynı vektörü <code>c()</code> ve <code>seq()</code> fonksiyonu ile de oluşturabiliriz. Ama bu örnek için daha uzun olacaktır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_len bill_dep flipper_len body_mass    sex year
1  Adelie Torgersen     39.1     18.7         181      3750   male 2007
2  Adelie Torgersen     39.5     17.4         186      3800 female 2007
3  Adelie Torgersen     40.3     18.0         195      3250 female 2007
4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5  Adelie Torgersen     36.7     19.3         193      3450 female 2007
6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">6</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_len bill_dep flipper_len body_mass    sex year
1  Adelie Torgersen     39.1     18.7         181      3750   male 2007
2  Adelie Torgersen     39.5     17.4         186      3800 female 2007
3  Adelie Torgersen     40.3     18.0         195      3250 female 2007
4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5  Adelie Torgersen     36.7     19.3         193      3450 female 2007
6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</code></pre>
</div>
</div>
<p>Sütun seçmek için kullandığımız indeksi önceden tanımladığımız bir vektör yardımıyla da yazabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>penguins[i, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_len bill_dep flipper_len body_mass    sex year
1  Adelie Torgersen     39.1     18.7         181      3750   male 2007
2  Adelie Torgersen     39.5     17.4         186      3800 female 2007
3  Adelie Torgersen     40.3     18.0         195      3250 female 2007
4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5  Adelie Torgersen     36.7     19.3         193      3450 female 2007
6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</code></pre>
</div>
</div>
<p>i’ye 1’den 6’ya kadar sayılardan oluşan bir vektör atadım ve onu da satır seçmek için kullandım.</p>
<p>Şimdi de ilk iki sütunu ve ilk 10 satırı seçelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species    island
1   Adelie Torgersen
2   Adelie Torgersen
3   Adelie Torgersen
4   Adelie Torgersen
5   Adelie Torgersen
6   Adelie Torgersen
7   Adelie Torgersen
8   Adelie Torgersen
9   Adelie Torgersen
10  Adelie Torgersen</code></pre>
</div>
</div>
<p>Gördüğünüz gibi oldukça basit bir şekilde verimizin bir alt kümesini aldık.</p>
<p>Şimdi de aynı işlemleri indeks yerine sütun isimleri kullanarak yapalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">c</span>(<span class="st">"species"</span>, <span class="st">"island"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species    island
1   Adelie Torgersen
2   Adelie Torgersen
3   Adelie Torgersen
4   Adelie Torgersen
5   Adelie Torgersen
6   Adelie Torgersen
7   Adelie Torgersen
8   Adelie Torgersen
9   Adelie Torgersen
10  Adelie Torgersen</code></pre>
</div>
</div>
<p>Bu sefer de sütun indeksleri yerine sütun isimlerini kullandık. Sütun isimlerini <code>"</code> içerisinde, yani character olarak tanımladım ve birden fazla değer olduğu için <code>c()</code> (combine) fonksiyonuyla bir vektör oluşturdum. Başta karmaşık gelebilir ama mantığını öğrendikten, yeterli sayıda alıştırma yaptıktan sonra oldukça basitleşecektir.</p>
<p>Şimdi de verimizin özet istatistiklerine bir bakalım. Bunun için <code>summary()</code> fonksiyonunu kullanabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species          island       bill_len        bill_dep    
 Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
 Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
 Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
                                 Mean   :43.92   Mean   :17.15  
                                 3rd Qu.:48.50   3rd Qu.:18.70  
                                 Max.   :59.60   Max.   :21.50  
                                 NA's   :2       NA's   :2      
  flipper_len      body_mass        sex           year     
 Min.   :172.0   Min.   :2700   female:165   Min.   :2007  
 1st Qu.:190.0   1st Qu.:3550   male  :168   1st Qu.:2007  
 Median :197.0   Median :4050   NA's  : 11   Median :2008  
 Mean   :200.9   Mean   :4202                Mean   :2008  
 3rd Qu.:213.0   3rd Qu.:4750                3rd Qu.:2009  
 Max.   :231.0   Max.   :6300                Max.   :2009  
 NA's   :2       NA's   :2                                 </code></pre>
</div>
</div>
<p><code>summary()</code> fonksiyonunu kullanarak her değer için özet istatistikleri görebiliyoruz. Eksik veri için kullanılan <code>NA</code> değerleri de dahil. Ayrıca factor değerlerimiz için bir frekans tablosu elde etmiş oluyoruz. Yani her bir kategoriden kaç adet olduğunu görebiliyoruz. Bunu yapmanın birden fazla yolu var ve bazıları daha kullanışlı. Bunlara da bir bakalım ancak öncelikle <code>species</code> değişkeni için kaç adet eşsiz (unique) değer olduğuna bakalım. Diğer kategorik değişkenler için de aynı yöntemi kullanabilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(penguins<span class="sc">$</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Adelie    Gentoo    Chinstrap
Levels: Adelie Chinstrap Gentoo</code></pre>
</div>
</div>
<p>Dikkat edin burada list ve özellikle de data.frame’lerde kullanılan yeni bir operatörle karşılaştık; <code>$</code> operatörü. Bu operatörü data.frame’lerin sütunlarına doğrudan erişmek için kullanabiliriz. Bir sütuna erişmek ve onu vektöre çevirip işlem yapmak istediğimizde en kullanışlı yöntem bu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>penguins<span class="sc">$</span>species</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [11] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [21] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [31] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [41] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [51] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [61] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [71] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [81] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
 [91] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
[101] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
[111] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
[121] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
[131] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
[141] Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie Adelie
[151] Adelie Adelie Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo
[161] Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo
[171] Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo
[181] Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo
[191] Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo Gentoo
 [ reached 'max' / getOption("max.print") -- omitted 144 entries ]
Levels: Adelie Chinstrap Gentoo</code></pre>
</div>
</div>
<p>Bakın <code>species</code> sütununu bir vektör olarak döndürdü.</p>
<p>Şimdi, biraz evvel dediğim gibi <code>summary()</code>, <code>table()</code> gibi fonksiyonlarla hem eşsiz değerlere hem de bu değerlerin sıklığına erişebiliriz. Ne gerek var <code>unique()</code> gibi fonksiyonlara diyebilirsiniz ancak çoğu zaman programatik olarak ihtiyaç duyabiliyoruz. Bu yüzden öğrenmekte fayda var.</p>
<p>Şimdi de bu eşsiz değerlerin sıklık tablosuna bakalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins<span class="sc">$</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Adelie Chinstrap    Gentoo 
      152        68       124 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins<span class="sc">$</span>island)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Biscoe     Dream Torgersen 
      168       124        52 </code></pre>
</div>
</div>
<p>Tek tek faktör değişkenlerimizin sıklık tablosuna baktığımıza göre şimdi de, iki farklı değişken kullanarak bakabiliriz.</p>
<p>Hangi adada hangi türden kaç tane penguen mevcut?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins<span class="sc">$</span>species, penguins<span class="sc">$</span>island)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            Biscoe Dream Torgersen
  Adelie        44    56        52
  Chinstrap      0    68         0
  Gentoo       124     0         0</code></pre>
</div>
</div>
<p>Gördüğünüz gibi iki değişkeni de kullanarak <code>table()</code> fonksiyonuyla bunu öğrenebiliyoruz.</p>
</section>
<section id="veri-cambazliği" class="level2">
<h2 class="anchored" data-anchor-id="veri-cambazliği">2. VERİ CAMBAZLIĞI</h2>
<p>Şu ana kadar bir data.frame üzerinden, R’da, vektörler, matrix’ler ve özellikle de data.frame’lerle yapabileceğimiz birçok temel işlemi gördük.</p>
<p>Şimdi bir veri analizi - veri bilimi iş akışının en mühim kısımlarından olan veri cambazlığını nasıl yapabileceğimize bakacağız. Bunun için Hadley Wickham’ın R for Data Science kitabında anlattığı şekliyle <code>sütun</code>, <code>satır</code> ve <code>grup</code> işlemlerini, base R kullanarak yapacağız. Gerçek dünya verileriyle uğraştığımızda bu kısım, bir veri bilimi iş akışının genellikle büyük çoğunluğunu oluşturuyor.</p>
<p>Bu bölümde yine palmerpenguins datasını kullanacağız ama bu sefer ham olan versiyonunu. Verinin ham hâlini kullanarak <code>penguins</code>’teki son hâline ulaşmaya çalışacağız. Bu veriye erişmek için <code>penguins_raw</code> yazabilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>penguins_raw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   studyName Sample Number                             Species Region    Island
1    PAL0708             1 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
2    PAL0708             2 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
3    PAL0708             3 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
4    PAL0708             4 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
5    PAL0708             5 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
6    PAL0708             6 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
7    PAL0708             7 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
8    PAL0708             8 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
9    PAL0708             9 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
10   PAL0708            10 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
11   PAL0708            11 Adelie Penguin (Pygoscelis adeliae) Anvers Torgersen
                Stage Individual ID Clutch Completion   Date Egg
1  Adult, 1 Egg Stage          N1A1               Yes 2007-11-11
2  Adult, 1 Egg Stage          N1A2               Yes 2007-11-11
3  Adult, 1 Egg Stage          N2A1               Yes 2007-11-16
4  Adult, 1 Egg Stage          N2A2               Yes 2007-11-16
5  Adult, 1 Egg Stage          N3A1               Yes 2007-11-16
6  Adult, 1 Egg Stage          N3A2               Yes 2007-11-16
7  Adult, 1 Egg Stage          N4A1                No 2007-11-15
8  Adult, 1 Egg Stage          N4A2                No 2007-11-15
9  Adult, 1 Egg Stage          N5A1               Yes 2007-11-09
10 Adult, 1 Egg Stage          N5A2               Yes 2007-11-09
11 Adult, 1 Egg Stage          N6A1               Yes 2007-11-09
   Culmen Length (mm) Culmen Depth (mm) Flipper Length (mm) Body Mass (g)
1                39.1              18.7                 181          3750
2                39.5              17.4                 186          3800
3                40.3              18.0                 195          3250
4                  NA                NA                  NA            NA
5                36.7              19.3                 193          3450
6                39.3              20.6                 190          3650
7                38.9              17.8                 181          3625
8                39.2              19.6                 195          4675
9                34.1              18.1                 193          3475
10               42.0              20.2                 190          4250
11               37.8              17.1                 186          3300
      Sex Delta 15 N (o/oo) Delta 13 C (o/oo)
1    MALE                NA                NA
2  FEMALE           8.94956         -24.69454
3  FEMALE           8.36821         -25.33302
4    &lt;NA&gt;                NA                NA
5  FEMALE           8.76651         -25.32426
6    MALE           8.66496         -25.29805
7  FEMALE           9.18718         -25.21799
8    MALE           9.46060         -24.89958
9    &lt;NA&gt;                NA                NA
10   &lt;NA&gt;           9.13362         -25.09368
11   &lt;NA&gt;           8.63243         -25.21315
                                Comments
1         Not enough blood for isotopes.
2                                   &lt;NA&gt;
3                                   &lt;NA&gt;
4                     Adult not sampled.
5                                   &lt;NA&gt;
6                                   &lt;NA&gt;
7  Nest never observed with full clutch.
8  Nest never observed with full clutch.
9              No blood sample obtained.
10  No blood sample obtained for sexing.
11  No blood sample obtained for sexing.
 [ reached 'max' / getOption("max.print") -- omitted 333 rows ]</code></pre>
</div>
</div>
<p>Şimdi veriye hızlıca göz atalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penguins_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  17 variables:
 $ studyName          : chr  "PAL0708" "PAL0708" "PAL0708" "PAL0708" ...
 $ Sample Number      : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Species            : chr  "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" ...
 $ Region             : chr  "Anvers" "Anvers" "Anvers" "Anvers" ...
 $ Island             : chr  "Torgersen" "Torgersen" "Torgersen" "Torgersen" ...
 $ Stage              : chr  "Adult, 1 Egg Stage" "Adult, 1 Egg Stage" "Adult, 1 Egg Stage" "Adult, 1 Egg Stage" ...
 $ Individual ID      : chr  "N1A1" "N1A2" "N2A1" "N2A2" ...
 $ Clutch Completion  : chr  "Yes" "Yes" "Yes" "Yes" ...
 $ Date Egg           : Date, format: "2007-11-11" "2007-11-11" ...
 $ Culmen Length (mm) : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ Culmen Depth (mm)  : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ Flipper Length (mm): num  181 186 195 NA 193 190 181 195 193 190 ...
 $ Body Mass (g)      : num  3750 3800 3250 NA 3450 ...
 $ Sex                : chr  "MALE" "FEMALE" "FEMALE" NA ...
 $ Delta 15 N (o/oo)  : num  NA 8.95 8.37 NA 8.77 ...
 $ Delta 13 C (o/oo)  : num  NA -24.7 -25.3 NA -25.3 ...
 $ Comments           : chr  "Not enough blood for isotopes." NA NA "Adult not sampled." ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  studyName         Sample Number      Species             Region         
 Length:344         Min.   :  1.00   Length:344         Length:344        
 Class :character   1st Qu.: 29.00   Class :character   Class :character  
 Mode  :character   Median : 58.00   Mode  :character   Mode  :character  
                    Mean   : 63.15                                        
                    3rd Qu.: 95.25                                        
                    Max.   :152.00                                        
                                                                          
    Island             Stage           Individual ID      Clutch Completion 
 Length:344         Length:344         Length:344         Length:344        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
    Date Egg          Culmen Length (mm) Culmen Depth (mm) Flipper Length (mm)
 Min.   :2007-11-09   Min.   :32.10      Min.   :13.10     Min.   :172.0      
 1st Qu.:2007-11-28   1st Qu.:39.23      1st Qu.:15.60     1st Qu.:190.0      
 Median :2008-11-09   Median :44.45      Median :17.30     Median :197.0      
 Mean   :2008-11-27   Mean   :43.92      Mean   :17.15     Mean   :200.9      
 3rd Qu.:2009-11-16   3rd Qu.:48.50      3rd Qu.:18.70     3rd Qu.:213.0      
 Max.   :2009-12-01   Max.   :59.60      Max.   :21.50     Max.   :231.0      
                      NA's   :2          NA's   :2         NA's   :2          
 Body Mass (g)      Sex            Delta 15 N (o/oo) Delta 13 C (o/oo)
 Min.   :2700   Length:344         Min.   : 7.632    Min.   :-27.02   
 1st Qu.:3550   Class :character   1st Qu.: 8.300    1st Qu.:-26.32   
 Median :4050   Mode  :character   Median : 8.652    Median :-25.83   
 Mean   :4202                      Mean   : 8.733    Mean   :-25.69   
 3rd Qu.:4750                      3rd Qu.: 9.172    3rd Qu.:-25.06   
 Max.   :6300                      Max.   :10.025    Max.   :-23.79   
 NA's   :2                         NA's   :14        NA's   :13       
   Comments        
 Length:344        
 Class :character  
 Mode  :character  
                   
                   
                   
                   </code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/penguins2.webp" class="img-fluid figure-img"></p>
<figcaption>Kaynak: <a href="https://allisonhorst.github.io/palmerpenguins/articles/art.html">Allison Horst</a></figcaption>
</figure>
</div>
<section id="sütun-işlemleri" class="level3">
<h3 class="anchored" data-anchor-id="sütun-işlemleri">SÜTUN İŞLEMLERİ</h3>
<p><code>penguins</code> verisi 8 değişkenden oluşuyordu ancak <code>penguins_raw</code> verisi 17 değişkenden oluşuyor.</p>
<p>Öncelikle <code>penguins</code>’te olan değişkenlerin bizim için önemli olduğunu varsayalım ve onları seçelim. penguins ismiyle çatışma olmasın diye önce verinin farklı isimli bir kopyasını oluşturacağım, ardından sütunları seçeceğim.</p>
<p>Daha önce de gördüğümüz gibi sütunlarla ilgili bir işlem yapmak için 2. boyutu, yani virgülün sağını kullanıyoruz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>peng_raw <span class="ot">&lt;-</span> penguins_raw</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_raw[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  studyName Sample Number                             Species
1   PAL0708             1 Adelie Penguin (Pygoscelis adeliae)
2   PAL0708             2 Adelie Penguin (Pygoscelis adeliae)
3   PAL0708             3 Adelie Penguin (Pygoscelis adeliae)
4   PAL0708             4 Adelie Penguin (Pygoscelis adeliae)
5   PAL0708             5 Adelie Penguin (Pygoscelis adeliae)
6   PAL0708             6 Adelie Penguin (Pygoscelis adeliae)</code></pre>
</div>
</div>
<p>Yukarıda gördüğünüz gibi istediğimiz sütunların indeksini bir vektör olarak yazarak seçim yapabiliyoruz.</p>
<p>Bunun için sütun isimlerini de tercih edebiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_raw[, <span class="fu">c</span>(<span class="st">"studyName"</span>, <span class="st">"Sample Number"</span>, <span class="st">"Species"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  studyName Sample Number                             Species
1   PAL0708             1 Adelie Penguin (Pygoscelis adeliae)
2   PAL0708             2 Adelie Penguin (Pygoscelis adeliae)
3   PAL0708             3 Adelie Penguin (Pygoscelis adeliae)
4   PAL0708             4 Adelie Penguin (Pygoscelis adeliae)
5   PAL0708             5 Adelie Penguin (Pygoscelis adeliae)
6   PAL0708             6 Adelie Penguin (Pygoscelis adeliae)</code></pre>
</div>
</div>
<p>Gördüğünüz gibi sonuç aynı.</p>
<p>Bu tür karmaşık verilerde indeksleri kullanıp seçim yapmak daha kolay olabiliyor ancak burada isimlere göre seçelim. Bu şekilde yaptığımız iş hataya daha az açık olacaktır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>names_raw <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Species"</span>, <span class="st">"Island"</span>, <span class="st">"Date Egg"</span>, <span class="st">"Culmen Length (mm)"</span>, <span class="st">"Culmen Depth (mm)"</span>,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Flipper Length (mm)"</span>, <span class="st">"Body Mass (g)"</span>, <span class="st">"Sex"</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>peng_sel <span class="ot">&lt;-</span> peng_raw[, names_raw]</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_sel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              Species    Island   Date Egg Culmen Length (mm)
1 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-11               39.1
2 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-11               39.5
3 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16               40.3
4 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16                 NA
5 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16               36.7
6 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16               39.3
  Culmen Depth (mm) Flipper Length (mm) Body Mass (g)    Sex
1              18.7                 181          3750   MALE
2              17.4                 186          3800 FEMALE
3              18.0                 195          3250 FEMALE
4                NA                  NA            NA   &lt;NA&gt;
5              19.3                 193          3450 FEMALE
6              20.6                 190          3650   MALE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(peng_sel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  8 variables:
 $ Species            : chr  "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" ...
 $ Island             : chr  "Torgersen" "Torgersen" "Torgersen" "Torgersen" ...
 $ Date Egg           : Date, format: "2007-11-11" "2007-11-11" ...
 $ Culmen Length (mm) : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ Culmen Depth (mm)  : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ Flipper Length (mm): num  181 186 195 NA 193 190 181 195 193 190 ...
 $ Body Mass (g)      : num  3750 3800 3250 NA 3450 ...
 $ Sex                : chr  "MALE" "FEMALE" "FEMALE" NA ...</code></pre>
</div>
</div>
<p>Şimdi de sütun isimlerini değiştirelim.</p>
<p>Camel case kullanılan isimler, büyük harfle başlayan isimler, birimler, boşluklar derken standart olmayan birçok şey var. Ben, tidy style guide’da belirtildiği gibi snake_case kullanmayı tercih ediyor, bunun daha işlevsel olduğunu düşünüyorum. Yani tüm isimleri küçük harflerle yazacağız, Türkçe karakter kullanmayacağız ve boşlukları <code>_</code> ile ayıracağız.</p>
<p>Sütun isimlerine -data.frame’de names() fonksiyonunu da colnames() fonksiyonunu da kullanabiliriz- değiştirmek istediğimiz isimleri atıyoruz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(peng_sel) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"species"</span>, <span class="st">"island"</span>, <span class="st">"year"</span>, <span class="st">"bill_len"</span>, <span class="st">"bill_dep"</span>, </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"flipper_len"</span>, <span class="st">"body_mass"</span>,<span class="st">"sex"</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_sel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              species    island       year bill_len bill_dep
1 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-11     39.1     18.7
2 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-11     39.5     17.4
3 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16     40.3     18.0
4 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16       NA       NA
5 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16     36.7     19.3
6 Adelie Penguin (Pygoscelis adeliae) Torgersen 2007-11-16     39.3     20.6
  flipper_len body_mass    sex
1         181      3750   MALE
2         186      3800 FEMALE
3         195      3250 FEMALE
4          NA        NA   &lt;NA&gt;
5         193      3450 FEMALE
6         190      3650   MALE</code></pre>
</div>
</div>
<p>Gördüğünüz gibi isimler <code>penguins</code> verisiyle aynı hâle geldi.</p>
<p>Şimdi de sütun yerlerini sıralayalım. Bunun için sütunları istediğimiz sırada, indeksleriyle seçeceğiz. <code>penguins</code> ile tek fark <code>year</code> değişkeninin yeri. Dolayısıyla <code>year</code> değişkeninin indeksini en sona koyuyoruz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>peng_relocate <span class="ot">&lt;-</span> peng_sel[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">3</span>)]</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              species    island bill_len bill_dep flipper_len
1 Adelie Penguin (Pygoscelis adeliae) Torgersen     39.1     18.7         181
2 Adelie Penguin (Pygoscelis adeliae) Torgersen     39.5     17.4         186
3 Adelie Penguin (Pygoscelis adeliae) Torgersen     40.3     18.0         195
4 Adelie Penguin (Pygoscelis adeliae) Torgersen       NA       NA          NA
5 Adelie Penguin (Pygoscelis adeliae) Torgersen     36.7     19.3         193
6 Adelie Penguin (Pygoscelis adeliae) Torgersen     39.3     20.6         190
  body_mass    sex       year
1      3750   MALE 2007-11-11
2      3800 FEMALE 2007-11-11
3      3250 FEMALE 2007-11-16
4        NA   &lt;NA&gt; 2007-11-16
5      3450 FEMALE 2007-11-16
6      3650   MALE 2007-11-16</code></pre>
</div>
</div>
<p>Bu iş de tamamdır!</p>
<p>Şimdi de görevimizi biraz daha zorlaştıralım. Her sütunun içindeki değerleri düzenleyeceğiz. Dikkat ettiyseniz <code>penguins</code> verisinde çok daha düzenli bir hâldeydi.</p>
<p>İlk olarak yılla başlayalım. Tarihi yıla çevirmemiz lazım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "2007-11-11" "2007-11-11" "2007-11-16" "2007-11-16" "2007-11-16"
  [6] "2007-11-16" "2007-11-15" "2007-11-15" "2007-11-09" "2007-11-09"
 [11] "2007-11-09" "2007-11-09" "2007-11-15" "2007-11-15" "2007-11-16"
 [16] "2007-11-16" "2007-11-12" "2007-11-12" "2007-11-16" "2007-11-16"
 [21] "2007-11-12" "2007-11-12" "2007-11-12" "2007-11-12" "2007-11-10"
 [26] "2007-11-10" "2007-11-12" "2007-11-12" "2007-11-10" "2007-11-10"
 [31] "2007-11-09" "2007-11-09" "2007-11-09" "2007-11-09" "2007-11-16"
 [36] "2007-11-16" "2007-11-16" "2007-11-16" "2007-11-13" "2007-11-13"
 [41] "2007-11-16" "2007-11-16" "2007-11-19" "2007-11-19" "2007-11-16"
 [46] "2007-11-16" "2007-11-13" "2007-11-13" "2007-11-13" "2007-11-13"
 [51] "2008-11-06" "2008-11-06" "2008-11-09" "2008-11-09" "2008-11-09"
 [56] "2008-11-09" "2008-11-15" "2008-11-15" "2008-11-15" "2008-11-15"
 [61] "2008-11-13" "2008-11-13" "2008-11-13" "2008-11-13" "2008-11-13"
 [66] "2008-11-13" "2008-11-06" "2008-11-06" "2008-11-11" "2008-11-11"
 [71] "2008-11-14" "2008-11-14" "2008-11-11" "2008-11-11" "2008-11-08"
 [76] "2008-11-08" "2008-11-06" "2008-11-06" "2008-11-09" "2008-11-09"
 [81] "2008-11-02" "2008-11-02" "2008-11-07" "2008-11-07" "2008-11-17"
 [86] "2008-11-17" "2008-11-08" "2008-11-08" "2008-11-08" "2008-11-08"
 [91] "2008-11-14" "2008-11-14" "2008-11-05" "2008-11-05" "2008-11-17"
 [96] "2008-11-17" "2008-11-08" "2008-11-08" "2008-11-10" "2008-11-10"
[101] "2009-11-09" "2009-11-09" "2009-11-15" "2009-11-15" "2009-11-15"
[106] "2009-11-15" "2009-11-15" "2009-11-15" "2009-11-20" "2009-11-20"
[111] "2009-11-12" "2009-11-12" "2009-11-15" "2009-11-15" "2009-11-17"
[116] "2009-11-17" "2009-11-18" "2009-11-18" "2009-11-22" "2009-11-22"
[121] "2009-11-17" "2009-11-17" "2009-11-16" "2009-11-16" "2009-11-18"
[126] "2009-11-18" "2009-11-21" "2009-11-21" "2009-11-18" "2009-11-18"
[131] "2009-11-23" "2009-11-23" "2009-11-10" "2009-11-10" "2009-11-13"
[136] "2009-11-13" "2009-11-16" "2009-11-16" "2009-11-16" "2009-11-16"
[141] "2009-11-14" "2009-11-14" "2009-11-16" "2009-11-16" "2009-11-16"
[146] "2009-11-16" "2009-11-13" "2009-11-13" "2009-11-17" "2009-11-17"
[151] "2009-11-17" "2009-11-17" "2007-11-27" "2007-11-27" "2007-11-27"
[156] "2007-11-27" "2007-11-18" "2007-11-18" "2007-11-27" "2007-11-27"
[161] "2007-11-27" "2007-11-27" "2007-11-27" "2007-11-27" "2007-11-29"
[166] "2007-11-29" "2007-12-03" "2007-12-03" "2007-11-27" "2007-11-27"
[171] "2007-11-27" "2007-11-27" "2007-11-27" "2007-11-27" "2007-11-27"
[176] "2007-11-27" "2007-11-29" "2007-11-29" "2007-11-29" "2007-11-29"
[181] "2007-11-29" "2007-11-29" "2007-11-29" "2007-11-29" "2007-12-03"
[186] "2007-12-03" "2008-11-13" "2008-11-13" "2008-11-02" "2008-11-02"
[191] "2008-11-09" "2008-11-09" "2008-11-04" "2008-11-04" "2008-11-04"
[196] "2008-11-04" "2008-11-03" "2008-11-03" "2008-11-09" "2008-11-09"
 [ reached 'max' / getOption("max.print") -- omitted 144 entries ]</code></pre>
</div>
</div>
<p>Gördüğünüz yıl vektöründen ay ve günü silmemiz gerekiyor. Bunu tarihle oynayarak da yapabiliriz, karakter vektörüne çevirip, yıldan sonrasını silerek de. Normal şartlarda ikincisi daha kolay olabilir ama şu an hâlihazırda verimiz <code>Date</code> tipinde olduğu için direkt yılı seçebiliriz. Tarihlerle uğraşmak ilk başlayanlar için biraz zor olabilir. <code>format()</code> fonksiyonunu kullanacağız, <code>"%Y"</code> ile yılı seçeceğiz. Onu da değiştirdiğimiz sütuna tekrardan atayacağız.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">format</span>(peng_relocate<span class="sc">$</span>year, <span class="st">"%Y"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              species    island bill_len bill_dep flipper_len
1 Adelie Penguin (Pygoscelis adeliae) Torgersen     39.1     18.7         181
2 Adelie Penguin (Pygoscelis adeliae) Torgersen     39.5     17.4         186
3 Adelie Penguin (Pygoscelis adeliae) Torgersen     40.3     18.0         195
4 Adelie Penguin (Pygoscelis adeliae) Torgersen       NA       NA          NA
5 Adelie Penguin (Pygoscelis adeliae) Torgersen     36.7     19.3         193
6 Adelie Penguin (Pygoscelis adeliae) Torgersen     39.3     20.6         190
  body_mass    sex year
1      3750   MALE 2007
2      3800 FEMALE 2007
3      3250 FEMALE 2007
4        NA   &lt;NA&gt; 2007
5      3450 FEMALE 2007
6      3650   MALE 2007</code></pre>
</div>
</div>
<p>Gördüğünüz gibi yıllar tamam! Sırada diğer değişkenler var.</p>
<p>İlk olarak tür isimlerini kısaltmamız lazım. En zor işlerden birisi bu! Özellikle de ilk başlayanlar için. <code>sub()</code> ve <code>gsub</code> fonksiyonu, karakter vektöründeki seçtiğimiz kısmı, istediğimiz karakterle değiştirir. <code>sub()</code> sadece ilk esleşmeyi değiştirdiği için onu kullanacağız. <code>" .*"</code> ile boşluk sonrasındaki tüm karakterleri seçiyoruz ve <code>""</code> ile replace ediyoruz. Yani siliyoruz. Çünkü <code>""</code> içinde hiçbir şey yok. Bu da bize tür isimlerinin boşluktan önceki kısmını veriyor tıpkı <code>penguins</code> verisinde olduğu gibi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>species <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">" .*"</span>, <span class="st">""</span>, peng_relocate<span class="sc">$</span>species)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">tolower</span>(peng_relocate<span class="sc">$</span>sex) <span class="co"># sex degiskenini kucuk harfe ceviriyoruz </span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species    island bill_len bill_dep flipper_len body_mass    sex year
1  Adelie Torgersen     39.1     18.7         181      3750   male 2007
2  Adelie Torgersen     39.5     17.4         186      3800 female 2007
3  Adelie Torgersen     40.3     18.0         195      3250 female 2007
4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5  Adelie Torgersen     36.7     19.3         193      3450 female 2007
6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</code></pre>
</div>
</div>
<p>Şu an <code>penguins</code> verisiyle aynı veriye sahibiz!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(penguins, peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Aaa! Değilmişiz! Fark ne acaba?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  8 variables:
 $ species    : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island     : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_len   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_dep   : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_len: int  181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass  : int  3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex        : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year       : int  2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  8 variables:
 $ species    : chr  "Adelie" "Adelie" "Adelie" "Adelie" ...
 $ island     : chr  "Torgersen" "Torgersen" "Torgersen" "Torgersen" ...
 $ bill_len   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_dep   : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_len: num  181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass  : num  3750 3800 3250 NA 3450 ...
 $ sex        : chr  "male" "female" "female" NA ...
 $ year       : chr  "2007" "2007" "2007" "2007" ...</code></pre>
</div>
</div>
<p>Gördüğünüz gibi sütun tipleri birbirinden farklı. Onları da değiştirelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>species <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(peng_relocate<span class="sc">$</span>species)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>island <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(peng_relocate<span class="sc">$</span>island)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>flipper_len <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(peng_relocate<span class="sc">$</span>flipper_len)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>body_mass <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(peng_relocate<span class="sc">$</span>body_mass)</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(peng_relocate<span class="sc">$</span>sex)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(peng_relocate<span class="sc">$</span>year)</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  8 variables:
 $ species    : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island     : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_len   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_dep   : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_len: int  181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass  : int  3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex        : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year       : int  2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
</div>
</div>
<p>Değişmesi gereken tüm sütunları tek tek değiştirdik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(penguins, peng_relocate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Gördüğünüz gibi artık verilerimiz eş! Hedefimize ulaştık, dağınık bir veriyi düzenli bir hâle getirdik.</p>
</section>
<section id="satir-işlemleri" class="level3">
<h3 class="anchored" data-anchor-id="satir-işlemleri">SATIR İŞLEMLERİ</h3>
<p><code>penguins_raw</code> verisini, <code>penguins</code> verisiyle eş bir hâle getirdiğimize göre hedefimize ulaştık ama bu yazının amacına ulaşması için satır ve grup işlemlerini de görmemiz gerekiyor. Sütunlarını düzenlediğimiz <code>peng_relocate</code> nesnesi üzerinde biraz oynayalım.</p>
<p>Şimdi yalnızca Biscoe adasındaki penguenleri incelediğimizi varsayalım. Verimizi Biscoe adasına göre filtreleyeceğiz. Filtreleme işlemi, R kullanmaya ilk başladığımda beni en çok zorlayan, kafamı en çok karıştıran şeylerden birisiydi. Anlamadığınızı düşündüğünüz yerde kodu parçalara bölüp, ne yaptığını anlamaya çalışın. Oldukça faydalı olacaktır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[peng_relocate<span class="sc">$</span>island <span class="sc">==</span> <span class="st">"Biscoe"</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species island bill_len bill_dep flipper_len body_mass    sex year
21  Adelie Biscoe     37.8     18.3         174      3400 female 2007
22  Adelie Biscoe     37.7     18.7         180      3600   male 2007
23  Adelie Biscoe     35.9     19.2         189      3800 female 2007
24  Adelie Biscoe     38.2     18.1         185      3950   male 2007
25  Adelie Biscoe     38.8     17.2         180      3800   male 2007
26  Adelie Biscoe     35.3     18.9         187      3800 female 2007
27  Adelie Biscoe     40.6     18.6         183      3550   male 2007
28  Adelie Biscoe     40.5     17.9         187      3200 female 2007
29  Adelie Biscoe     37.9     18.6         172      3150 female 2007
30  Adelie Biscoe     40.5     18.9         180      3950   male 2007
51  Adelie Biscoe     39.6     17.7         186      3500 female 2008
52  Adelie Biscoe     40.1     18.9         188      4300   male 2008
53  Adelie Biscoe     35.0     17.9         190      3450 female 2008
54  Adelie Biscoe     42.0     19.5         200      4050   male 2008
55  Adelie Biscoe     34.5     18.1         187      2900 female 2008
56  Adelie Biscoe     41.4     18.6         191      3700   male 2008
57  Adelie Biscoe     39.0     17.5         186      3550 female 2008
58  Adelie Biscoe     40.6     18.8         193      3800   male 2008
59  Adelie Biscoe     36.5     16.6         181      2850 female 2008
60  Adelie Biscoe     37.6     19.1         194      3750   male 2008
61  Adelie Biscoe     35.7     16.9         185      3150 female 2008
62  Adelie Biscoe     41.3     21.1         195      4400   male 2008
63  Adelie Biscoe     37.6     17.0         185      3600 female 2008
64  Adelie Biscoe     41.1     18.2         192      4050   male 2008
65  Adelie Biscoe     36.4     17.1         184      2850 female 2008
 [ reached 'max' / getOption("max.print") -- omitted 143 rows ]</code></pre>
</div>
</div>
<p>Bakın sadece Biscoe adasındaki penguenleri seçmiş olduk. Peki burada ne yaptık?</p>
<p>Öncelikle <code>island</code> vektörü içindeki adalardan hangilerinin Biscoe olduğunu mantıksal olarak sınayacağız. Bunu <code>==</code> operatörüyle yapacağız. Bu, bize <code>TRUE</code> <code>FALSE</code> olarak dönecek.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>peng_relocate<span class="sc">$</span>island <span class="sc">==</span> <span class="st">"Biscoe"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[169]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[193]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [ reached 'max' / getOption("max.print") -- omitted 144 entries ]</code></pre>
</div>
</div>
<p>Buradan <code>TRUE</code> olanları seçmemiz gerekiyor. <code>peng_relocate</code> verimizin satır indeksi yerine bu mantıksal sonucu koyduğumuzda, <code>TRUE</code> olan satırları seçecektir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>peng_biscoe <span class="ot">&lt;-</span> peng_relocate[peng_relocate<span class="sc">$</span>island <span class="sc">==</span> <span class="st">"Biscoe"</span>, ]</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_biscoe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species island bill_len bill_dep flipper_len body_mass    sex year
21  Adelie Biscoe     37.8     18.3         174      3400 female 2007
22  Adelie Biscoe     37.7     18.7         180      3600   male 2007
23  Adelie Biscoe     35.9     19.2         189      3800 female 2007
24  Adelie Biscoe     38.2     18.1         185      3950   male 2007
25  Adelie Biscoe     38.8     17.2         180      3800   male 2007
26  Adelie Biscoe     35.3     18.9         187      3800 female 2007</code></pre>
</div>
</div>
<p>Gördüğünüz gibi Biscoe adasındaki penguenleri seçtik ve <code>peng_biscoe</code> isimli bir nesneye atadık.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(peng_biscoe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species          island       bill_len        bill_dep    
 Adelie   : 44   Biscoe   :168   Min.   :34.50   Min.   :13.10  
 Chinstrap:  0   Dream    :  0   1st Qu.:42.00   1st Qu.:14.50  
 Gentoo   :124   Torgersen:  0   Median :45.80   Median :15.50  
                                 Mean   :45.26   Mean   :15.87  
                                 3rd Qu.:48.70   3rd Qu.:17.00  
                                 Max.   :59.60   Max.   :21.10  
                                 NA's   :1       NA's   :1      
  flipper_len      body_mass        sex          year     
 Min.   :172.0   Min.   :2850   female:80   Min.   :2007  
 1st Qu.:199.5   1st Qu.:4200   male  :83   1st Qu.:2007  
 Median :214.0   Median :4775   NA's  : 5   Median :2008  
 Mean   :209.7   Mean   :4716               Mean   :2008  
 3rd Qu.:220.0   3rd Qu.:5325               3rd Qu.:2009  
 Max.   :231.0   Max.   :6300               Max.   :2009  
 NA's   :1       NA's   :1                                </code></pre>
</div>
</div>
<p>Verinin özet istatistiklerine göz attığımızda bazı <code>NA</code> (Not Available - eksik değer) değerlerin olduğunu görüyoruz. Bu değerleri istemediğimizi ve onlardan kurtulmak istediğimizi varsayalım. Bunun için yine filtreleme yapabiliriz.</p>
<p>Öncelikle en fazla NA değerine sahip <code>sex</code> değişkenindeki NA’lara bir bakalım. Bunun için <code>is.na()</code> isimli bir fonksiyonumuz var.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(peng_biscoe<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[157] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE</code></pre>
</div>
</div>
<p>Gördüğünüz gibi yine mantıksal bir sonuç döndü. Şimdi bu sonuca göre bir filtreleme yapalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>peng_biscoe[<span class="fu">is.na</span>(peng_biscoe<span class="sc">$</span>sex), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    species island bill_len bill_dep flipper_len body_mass  sex year
179  Gentoo Biscoe     44.5     14.3         216      4100 &lt;NA&gt; 2007
219  Gentoo Biscoe     46.2     14.4         214      4650 &lt;NA&gt; 2008
257  Gentoo Biscoe     47.3     13.8         216      4725 &lt;NA&gt; 2009
269  Gentoo Biscoe     44.5     15.7         217      4875 &lt;NA&gt; 2009
272  Gentoo Biscoe       NA       NA          NA        NA &lt;NA&gt; 2009</code></pre>
</div>
</div>
<p>NA değerleri seçmiş olduk ancak biz NA değerleri seçmek değil, silmek istiyorduk. Burada <code>!</code> operatörünü kullanacağız. Bu operatörümüz, bize “o” olmayan sonucu döndürecek.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>peng_biscoe_compl <span class="ot">&lt;-</span> peng_biscoe[<span class="sc">!</span><span class="fu">is.na</span>(peng_biscoe<span class="sc">$</span>sex), ]</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(peng_biscoe_compl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species island bill_len bill_dep flipper_len body_mass    sex year
21  Adelie Biscoe     37.8     18.3         174      3400 female 2007
22  Adelie Biscoe     37.7     18.7         180      3600   male 2007
23  Adelie Biscoe     35.9     19.2         189      3800 female 2007
24  Adelie Biscoe     38.2     18.1         185      3950   male 2007
25  Adelie Biscoe     38.8     17.2         180      3800   male 2007
26  Adelie Biscoe     35.3     18.9         187      3800 female 2007</code></pre>
</div>
</div>
<p>Evet şu an NA değerlere sahip olmayan <code>sex</code> değişkenine göre bir filtreleme yaptık.</p>
<p>Veriye tekrardan göz atalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(peng_biscoe_compl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species          island       bill_len        bill_dep    
 Adelie   : 44   Biscoe   :163   Min.   :34.50   Min.   :13.10  
 Chinstrap:  0   Dream    :  0   1st Qu.:41.85   1st Qu.:14.50  
 Gentoo   :119   Torgersen:  0   Median :45.80   Median :15.60  
                                 Mean   :45.25   Mean   :15.91  
                                 3rd Qu.:48.75   3rd Qu.:17.00  
                                 Max.   :59.60   Max.   :21.10  
  flipper_len      body_mass        sex          year     
 Min.   :172.0   Min.   :2850   female:80   Min.   :2007  
 1st Qu.:198.5   1st Qu.:4200   male  :83   1st Qu.:2007  
 Median :213.0   Median :4800               Median :2008  
 Mean   :209.6   Mean   :4719               Mean   :2008  
 3rd Qu.:220.0   3rd Qu.:5350               3rd Qu.:2009  
 Max.   :231.0   Max.   :6300               Max.   :2009  </code></pre>
</div>
</div>
<p>Tüm NA değerlerden kurtulmuşuz. Çünkü <code>bill_len</code>, <code>bill_dep</code>, <code>flipper_len</code> ve <code>body_mass</code> değişkenlerindeki tek NA değeri 272. satırdaydı ve bu satırdaki <code>sex</code> değeri de NA olduğu için o gidince hepsi gitmiş.</p>
<p>Şimdi 48 mm’den daha küçük <code>bill_len</code> ve 5000 g’den daha büyük <code>body_mass</code> değerlerine göre filtrelememiz gerektiğini düşünelim. Eğer birden fazla değişkene göre filtreleme yapmamız gerekiyorsa <code>ve</code> için <code>&amp;</code> operatörünü, <code>veya</code> için ise <code>|</code> operatörünü kullanıyoruz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>peng_biscoe_filt <span class="ot">&lt;-</span> peng_biscoe_compl[</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  peng_biscoe_compl<span class="sc">$</span>bill_len <span class="sc">&lt;</span> <span class="dv">48</span> <span class="sc">&amp;</span> peng_biscoe_compl<span class="sc">$</span>body_mass <span class="sc">&gt;</span> <span class="dv">5000</span>, </span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>peng_biscoe_filt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    species island bill_len bill_dep flipper_len body_mass    sex year
157  Gentoo Biscoe     47.6     14.5         215      5400   male 2007
160  Gentoo Biscoe     46.7     15.3         219      5200   male 2007
162  Gentoo Biscoe     46.8     15.4         215      5150   male 2007
176  Gentoo Biscoe     46.3     15.8         215      5050   male 2007
178  Gentoo Biscoe     46.1     15.1         215      5100   male 2007
180  Gentoo Biscoe     47.8     15.0         215      5650   male 2007
183  Gentoo Biscoe     47.3     15.3         222      5250   male 2007
185  Gentoo Biscoe     45.1     14.5         207      5050 female 2007
190  Gentoo Biscoe     44.4     17.3         219      5250   male 2008
201  Gentoo Biscoe     44.9     13.3         213      5100 female 2008
202  Gentoo Biscoe     45.2     15.8         215      5300   male 2008
208  Gentoo Biscoe     45.0     15.4         220      5050   male 2008
214  Gentoo Biscoe     46.2     14.9         221      5300   male 2008
226  Gentoo Biscoe     46.5     14.8         217      5200 female 2008
232  Gentoo Biscoe     45.2     16.4         223      5950   male 2008
258  Gentoo Biscoe     46.8     16.1         215      5500   male 2009
275  Gentoo Biscoe     45.2     14.8         212      5200 female 2009</code></pre>
</div>
</div>
<p>Gördüğünüz gibi filtreledik. Yalnızca Biscoe adasındaki Gentoo türü penguenlerin bir kısmı bu boyutlara sahipmiş.</p>
<p>Filtrelediğimiz veriyi bir grafikte görelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>)) <span class="co"># mfrow ile grafigi 2 satira bolduk, mar ile margin ayarladik</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  peng_biscoe_compl<span class="sc">$</span>bill_len,</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  peng_biscoe_compl<span class="sc">$</span>body_mass,</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Bill Length [mm]"</span>,                      <span class="co"># x ekseni basligi</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Body Mass [g]"</span>,                         <span class="co"># y ekseni basligi</span></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">20</span>                                        <span class="co"># pch (plot characters) nokta sekli icin</span></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb97-9"><a href="#cb97-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(                                             <span class="co"># filtreledigimiz degerleri kirmizi bir diktortgen ile belirttik</span></span>
<span id="cb97-10"><a href="#cb97-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">xleft =</span> <span class="fu">min</span>(peng_biscoe_filt<span class="sc">$</span>bill_len) <span class="sc">-</span> <span class="fl">0.2</span> ,  <span class="co"># minimum x ekseni degeri - 0.2</span></span>
<span id="cb97-11"><a href="#cb97-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ybottom =</span> <span class="fu">min</span>(peng_biscoe_filt<span class="sc">$</span>body_mass) <span class="sc">-</span> <span class="dv">20</span>, <span class="co"># minimum y ekseni degeri - 20</span></span>
<span id="cb97-12"><a href="#cb97-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">xright =</span> <span class="fu">max</span>(peng_biscoe_filt<span class="sc">$</span>bill_len) <span class="sc">+</span> <span class="fl">0.2</span>,  <span class="co"># maksimum x ekseni degeri + 0.2</span></span>
<span id="cb97-13"><a href="#cb97-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ytop =</span> <span class="fu">max</span>(peng_biscoe_filt<span class="sc">$</span>body_mass) <span class="sc">+</span> <span class="dv">50</span>,    <span class="co"># maksimum y ekseni degeri + 50</span></span>
<span id="cb97-14"><a href="#cb97-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">border =</span> <span class="st">"red"</span>,                                 <span class="co"># kirmizi rengi </span></span>
<span id="cb97-15"><a href="#cb97-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>                                         <span class="co"># lwd (linewidth) cizgi kalinligi</span></span>
<span id="cb97-16"><a href="#cb97-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb97-17"><a href="#cb97-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb97-18"><a href="#cb97-18" aria-hidden="true" tabindex="-1"></a>  peng_biscoe_filt<span class="sc">$</span>bill_len, </span>
<span id="cb97-19"><a href="#cb97-19" aria-hidden="true" tabindex="-1"></a>  peng_biscoe_filt<span class="sc">$</span>body_mass,</span>
<span id="cb97-20"><a href="#cb97-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Bill Length [mm]"</span>,</span>
<span id="cb97-21"><a href="#cb97-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Body Mass [g]"</span>,</span>
<span id="cb97-22"><a href="#cb97-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">20</span></span>
<span id="cb97-23"><a href="#cb97-23" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Grafik, filtrelediğimiz değerleri daha iyi görmenizi sağlamıştır diye düşünüyorum.</p>
<p>Şimdi de tekrardan <code>peng_biscoe_compl</code> verisini kullanarak 2008 ve 2009 yıllarındaki verileri filtreleyelim. Bunun için yine birden fazla yol var ancak biz bu sefer <code>%in%</code> operatörünü kullanacağız. R’da <code>%in%</code> operatörü, birden fazla değerle filtreleme yapıldığında kullanılıyor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>peng_biscoe_compl[peng_biscoe_compl<span class="sc">$</span>year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2008</span>, <span class="dv">2009</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    species island bill_len bill_dep flipper_len body_mass    sex year
51   Adelie Biscoe     39.6     17.7         186      3500 female 2008
52   Adelie Biscoe     40.1     18.9         188      4300   male 2008
53   Adelie Biscoe     35.0     17.9         190      3450 female 2008
54   Adelie Biscoe     42.0     19.5         200      4050   male 2008
55   Adelie Biscoe     34.5     18.1         187      2900 female 2008
56   Adelie Biscoe     41.4     18.6         191      3700   male 2008
57   Adelie Biscoe     39.0     17.5         186      3550 female 2008
58   Adelie Biscoe     40.6     18.8         193      3800   male 2008
59   Adelie Biscoe     36.5     16.6         181      2850 female 2008
60   Adelie Biscoe     37.6     19.1         194      3750   male 2008
61   Adelie Biscoe     35.7     16.9         185      3150 female 2008
62   Adelie Biscoe     41.3     21.1         195      4400   male 2008
63   Adelie Biscoe     37.6     17.0         185      3600 female 2008
64   Adelie Biscoe     41.1     18.2         192      4050   male 2008
65   Adelie Biscoe     36.4     17.1         184      2850 female 2008
66   Adelie Biscoe     41.6     18.0         192      3950   male 2008
67   Adelie Biscoe     35.5     16.2         195      3350 female 2008
68   Adelie Biscoe     41.1     19.1         188      4100   male 2008
101  Adelie Biscoe     35.0     17.9         192      3725 female 2009
102  Adelie Biscoe     41.0     20.0         203      4725   male 2009
103  Adelie Biscoe     37.7     16.0         183      3075 female 2009
104  Adelie Biscoe     37.8     20.0         190      4250   male 2009
105  Adelie Biscoe     37.9     18.6         193      2925 female 2009
106  Adelie Biscoe     39.7     18.9         184      3550   male 2009
107  Adelie Biscoe     38.6     17.2         199      3750 female 2009
 [ reached 'max' / getOption("max.print") -- omitted 95 rows ]</code></pre>
</div>
</div>
<p>Bu iş de tamam!</p>
<p>Sırada bir başka satır işlemi olan sıralama var. Sıralamayı base R ile yaparken <code>order()</code> fonksiyonunu kullanıyoruz. Bir de base R’a native pipe - <code>|&gt;</code> geldikten sonra çıkan <code>sort_by()</code> fonksiyonu var. İkisine de bakacağız.</p>
<p><code>order()</code> fonksiyonu bir vektörün sıralanmış indekslerini veriyor. Biz de bu indeksleri satır indeksi yerine kullanarak sıralama yapabiliyoruz.</p>
<p>Mesela filtrelemeden önceki verimiz olan <code>peng_relocate</code> verisinin <code>bill_len</code> sütunuyla <code>order()</code> fonksiyonunu kullanalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">order</span>(peng_relocate<span class="sc">$</span>bill_len)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 143  99  71  93   9  19  55  15  81  53 101  84 125  26  67  75 137  61
 [19]  91 119  23  69  43  49 149 151  79  95 121  87  35  65  41  59  16 148
 [37]   5  83 133  88  45 139  32  78  85 118 145  48 134  39  60  63  22 103
 [55] 122  11  12  21 104 150  29 105  97 109 111 135  24 108  89 131  14 107
 [73] 117  17  25  37 127   7  90  57 129 146   1   8  36 147   6   2  31  33
 [91]  46  51  73  94 115  72 106 113 140  40  52 123 138 141   3  98  28  30
[109]  27  58 126 142 144  42  96  34  77 163 307 102  13  47  64  68  92 120
[127] 136  62  86  56 124 128 152  66 259  70  10  54 169  80  38 114  50 297
[145]  18 309 331 189 116 193  76 184  82 177 132 100 110 211 299 161 261 239
[163] 221 265 341 198 209 191  44 130 190 179 247 269 201 237 208 174 185 205
[181] 202 231 232 275 282 333 195 213 159 280 165 199 210 245 320 112 336 215
[199] 329 339
 [ reached 'max' / getOption("max.print") -- omitted 144 entries ]</code></pre>
</div>
</div>
<p>Gördüğünüz gibi bize bir indeks verdi. Bu indeksle sıralama yapalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[<span class="fu">order</span>(peng_relocate<span class="sc">$</span>bill_len), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    species    island bill_len bill_dep flipper_len body_mass    sex year
143  Adelie     Dream     32.1     15.5         188      3050 female 2009
99   Adelie     Dream     33.1     16.1         178      2900 female 2008
71   Adelie Torgersen     33.5     19.0         190      3600 female 2008
93   Adelie     Dream     34.0     17.1         185      3400 female 2008
9    Adelie Torgersen     34.1     18.1         193      3475   &lt;NA&gt; 2007
19   Adelie Torgersen     34.4     18.4         184      3325 female 2007
55   Adelie    Biscoe     34.5     18.1         187      2900 female 2008
15   Adelie Torgersen     34.6     21.1         198      4400   male 2007
81   Adelie Torgersen     34.6     17.2         189      3200 female 2008
53   Adelie    Biscoe     35.0     17.9         190      3450 female 2008
101  Adelie    Biscoe     35.0     17.9         192      3725 female 2009
84   Adelie Torgersen     35.1     19.4         193      4200   male 2008
125  Adelie Torgersen     35.2     15.9         186      3050 female 2009
26   Adelie    Biscoe     35.3     18.9         187      3800 female 2007
67   Adelie    Biscoe     35.5     16.2         195      3350 female 2008
75   Adelie Torgersen     35.5     17.5         190      3700 female 2008
137  Adelie     Dream     35.6     17.5         191      3175 female 2009
61   Adelie    Biscoe     35.7     16.9         185      3150 female 2008
91   Adelie     Dream     35.7     18.0         202      3550 female 2008
119  Adelie Torgersen     35.7     17.0         189      3350 female 2009
23   Adelie    Biscoe     35.9     19.2         189      3800 female 2007
69   Adelie Torgersen     35.9     16.6         190      3050 female 2008
43   Adelie     Dream     36.0     18.5         186      3100 female 2007
49   Adelie     Dream     36.0     17.9         190      3450 female 2007
149  Adelie     Dream     36.0     17.8         195      3450 female 2009
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p>Ve verimiz sıralandı.</p>
<p><code>sort_by()</code> ise daha fonksiyonel bir yaklaşımdan geliyor. Şimdi de onu deneyelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort_by</span>(peng_relocate, peng_relocate<span class="sc">$</span>bill_len)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    species    island bill_len bill_dep flipper_len body_mass    sex year
143  Adelie     Dream     32.1     15.5         188      3050 female 2009
99   Adelie     Dream     33.1     16.1         178      2900 female 2008
71   Adelie Torgersen     33.5     19.0         190      3600 female 2008
93   Adelie     Dream     34.0     17.1         185      3400 female 2008
9    Adelie Torgersen     34.1     18.1         193      3475   &lt;NA&gt; 2007
19   Adelie Torgersen     34.4     18.4         184      3325 female 2007
55   Adelie    Biscoe     34.5     18.1         187      2900 female 2008
15   Adelie Torgersen     34.6     21.1         198      4400   male 2007
81   Adelie Torgersen     34.6     17.2         189      3200 female 2008
53   Adelie    Biscoe     35.0     17.9         190      3450 female 2008
101  Adelie    Biscoe     35.0     17.9         192      3725 female 2009
84   Adelie Torgersen     35.1     19.4         193      4200   male 2008
125  Adelie Torgersen     35.2     15.9         186      3050 female 2009
26   Adelie    Biscoe     35.3     18.9         187      3800 female 2007
67   Adelie    Biscoe     35.5     16.2         195      3350 female 2008
75   Adelie Torgersen     35.5     17.5         190      3700 female 2008
137  Adelie     Dream     35.6     17.5         191      3175 female 2009
61   Adelie    Biscoe     35.7     16.9         185      3150 female 2008
91   Adelie     Dream     35.7     18.0         202      3550 female 2008
119  Adelie Torgersen     35.7     17.0         189      3350 female 2009
23   Adelie    Biscoe     35.9     19.2         189      3800 female 2007
69   Adelie Torgersen     35.9     16.6         190      3050 female 2008
43   Adelie     Dream     36.0     18.5         186      3100 female 2007
49   Adelie     Dream     36.0     17.9         190      3450 female 2007
149  Adelie     Dream     36.0     17.8         195      3450 female 2009
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p>Eğer azalan bir sıralama istiyorsak <code>decreasing</code> argümanına <code>TRUE</code> değerini vermeli ya da değişkenin başına <code>-</code> eklemeliyiz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[<span class="fu">order</span>(peng_relocate<span class="sc">$</span>bill_len, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
186    Gentoo Biscoe     59.6     17.0         230      6050   male 2007
294 Chinstrap  Dream     58.0     17.8         181      3700 female 2007
254    Gentoo Biscoe     55.9     17.0         228      5600   male 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
268    Gentoo Biscoe     55.1     16.0         230      5850   male 2009
216    Gentoo Biscoe     54.3     15.7         231      5650   male 2008
308 Chinstrap  Dream     54.2     20.8         201      4300   male 2008
316 Chinstrap  Dream     53.5     19.9         205      4500   male 2008
260    Gentoo Biscoe     53.4     15.8         219      5500   male 2009
306 Chinstrap  Dream     52.8     20.0         205      4550   male 2008
281 Chinstrap  Dream     52.7     19.8         197      3725   male 2007
234    Gentoo Biscoe     52.5     15.6         221      5450   male 2009
244    Gentoo Biscoe     52.2     17.1         228      5400   male 2009
332 Chinstrap  Dream     52.2     18.8         197      3450   male 2009
242    Gentoo Biscoe     52.1     17.0         230      5550   male 2009
290 Chinstrap  Dream     52.0     18.1         201      4050   male 2007
302 Chinstrap  Dream     52.0     19.0         197      4150   male 2007
314 Chinstrap  Dream     52.0     20.7         210      4800   male 2008
337 Chinstrap  Dream     51.9     19.5         206      3950   male 2009
288 Chinstrap  Dream     51.7     20.3         194      3775   male 2007
266    Gentoo Biscoe     51.5     16.3         230      5500   male 2009
325 Chinstrap  Dream     51.5     18.7         187      3250   male 2009
328 Chinstrap  Dream     51.4     19.0         201      3950   male 2009
240    Gentoo Biscoe     51.3     14.2         218      5300   male 2009
279 Chinstrap  Dream     51.3     19.2         193      3650   male 2007
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[<span class="fu">order</span>(<span class="sc">-</span>peng_relocate<span class="sc">$</span>bill_len), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
186    Gentoo Biscoe     59.6     17.0         230      6050   male 2007
294 Chinstrap  Dream     58.0     17.8         181      3700 female 2007
254    Gentoo Biscoe     55.9     17.0         228      5600   male 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
268    Gentoo Biscoe     55.1     16.0         230      5850   male 2009
216    Gentoo Biscoe     54.3     15.7         231      5650   male 2008
308 Chinstrap  Dream     54.2     20.8         201      4300   male 2008
316 Chinstrap  Dream     53.5     19.9         205      4500   male 2008
260    Gentoo Biscoe     53.4     15.8         219      5500   male 2009
306 Chinstrap  Dream     52.8     20.0         205      4550   male 2008
281 Chinstrap  Dream     52.7     19.8         197      3725   male 2007
234    Gentoo Biscoe     52.5     15.6         221      5450   male 2009
244    Gentoo Biscoe     52.2     17.1         228      5400   male 2009
332 Chinstrap  Dream     52.2     18.8         197      3450   male 2009
242    Gentoo Biscoe     52.1     17.0         230      5550   male 2009
290 Chinstrap  Dream     52.0     18.1         201      4050   male 2007
302 Chinstrap  Dream     52.0     19.0         197      4150   male 2007
314 Chinstrap  Dream     52.0     20.7         210      4800   male 2008
337 Chinstrap  Dream     51.9     19.5         206      3950   male 2009
288 Chinstrap  Dream     51.7     20.3         194      3775   male 2007
266    Gentoo Biscoe     51.5     16.3         230      5500   male 2009
325 Chinstrap  Dream     51.5     18.7         187      3250   male 2009
328 Chinstrap  Dream     51.4     19.0         201      3950   male 2009
240    Gentoo Biscoe     51.3     14.2         218      5300   male 2009
279 Chinstrap  Dream     51.3     19.2         193      3650   male 2007
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p>Gördüğünüz gibi büyükten küçüğe bir şekilde sıraladık.</p>
<p><code>sort_by()</code> ile de aynı şekilde, değişkenin başına <code>-</code> ekleyerek azalan bir biçimde sıralayabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort_by</span>(peng_relocate, <span class="sc">-</span>peng_relocate<span class="sc">$</span>bill_len)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
186    Gentoo Biscoe     59.6     17.0         230      6050   male 2007
294 Chinstrap  Dream     58.0     17.8         181      3700 female 2007
254    Gentoo Biscoe     55.9     17.0         228      5600   male 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
268    Gentoo Biscoe     55.1     16.0         230      5850   male 2009
216    Gentoo Biscoe     54.3     15.7         231      5650   male 2008
308 Chinstrap  Dream     54.2     20.8         201      4300   male 2008
316 Chinstrap  Dream     53.5     19.9         205      4500   male 2008
260    Gentoo Biscoe     53.4     15.8         219      5500   male 2009
306 Chinstrap  Dream     52.8     20.0         205      4550   male 2008
281 Chinstrap  Dream     52.7     19.8         197      3725   male 2007
234    Gentoo Biscoe     52.5     15.6         221      5450   male 2009
244    Gentoo Biscoe     52.2     17.1         228      5400   male 2009
332 Chinstrap  Dream     52.2     18.8         197      3450   male 2009
242    Gentoo Biscoe     52.1     17.0         230      5550   male 2009
290 Chinstrap  Dream     52.0     18.1         201      4050   male 2007
302 Chinstrap  Dream     52.0     19.0         197      4150   male 2007
314 Chinstrap  Dream     52.0     20.7         210      4800   male 2008
337 Chinstrap  Dream     51.9     19.5         206      3950   male 2009
288 Chinstrap  Dream     51.7     20.3         194      3775   male 2007
266    Gentoo Biscoe     51.5     16.3         230      5500   male 2009
325 Chinstrap  Dream     51.5     18.7         187      3250   male 2009
328 Chinstrap  Dream     51.4     19.0         201      3950   male 2009
240    Gentoo Biscoe     51.3     14.2         218      5300   male 2009
279 Chinstrap  Dream     51.3     19.2         193      3650   male 2007
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p>Çoğu zaman sıralamaları birden fazla değişkenle yapmak isteyebiliriz. Bu durumda da <code>order()</code> fonksiyonuna diğer değişken isimlerini eklememiz gerekiyor.</p>
<p>Öncelikle yıla göre, sonrasında da gaga uzunluğuna göre büyükten küçüğe sıralayalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[<span class="fu">order</span>(<span class="sc">-</span>peng_relocate<span class="sc">$</span>year, <span class="sc">-</span>peng_relocate<span class="sc">$</span>bill_len), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
254    Gentoo Biscoe     55.9     17.0         228      5600   male 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
268    Gentoo Biscoe     55.1     16.0         230      5850   male 2009
260    Gentoo Biscoe     53.4     15.8         219      5500   male 2009
234    Gentoo Biscoe     52.5     15.6         221      5450   male 2009
244    Gentoo Biscoe     52.2     17.1         228      5400   male 2009
332 Chinstrap  Dream     52.2     18.8         197      3450   male 2009
242    Gentoo Biscoe     52.1     17.0         230      5550   male 2009
337 Chinstrap  Dream     51.9     19.5         206      3950   male 2009
266    Gentoo Biscoe     51.5     16.3         230      5500   male 2009
325 Chinstrap  Dream     51.5     18.7         187      3250   male 2009
328 Chinstrap  Dream     51.4     19.0         201      3950   male 2009
240    Gentoo Biscoe     51.3     14.2         218      5300   male 2009
252    Gentoo Biscoe     51.1     16.5         225      5250   male 2009
321 Chinstrap  Dream     50.9     17.9         196      3675 female 2009
238    Gentoo Biscoe     50.8     17.3         228      5600   male 2009
248    Gentoo Biscoe     50.8     15.7         226      5200   male 2009
322 Chinstrap  Dream     50.8     18.5         201      4450   male 2009
343 Chinstrap  Dream     50.8     19.0         210      4100   male 2009
330 Chinstrap  Dream     50.7     19.7         203      4050   male 2009
263    Gentoo Biscoe     50.5     15.2         216      5000 female 2009
274    Gentoo Biscoe     50.4     15.7         222      5750   male 2009
335 Chinstrap  Dream     50.2     18.8         202      3800   male 2009
344 Chinstrap  Dream     50.2     18.7         198      3775 female 2009
323 Chinstrap  Dream     50.1     17.9         190      3400 female 2009
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p><code>sort_by</code> fonksiyonuyla da aşağıdaki şekilde sıralayabilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort_by</span>(peng_relocate, <span class="fu">list</span>(<span class="sc">-</span>peng_relocate<span class="sc">$</span>year, <span class="sc">-</span>peng_relocate<span class="sc">$</span>bill_len))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species island bill_len bill_dep flipper_len body_mass    sex year
254    Gentoo Biscoe     55.9     17.0         228      5600   male 2009
340 Chinstrap  Dream     55.8     19.8         207      4000   male 2009
268    Gentoo Biscoe     55.1     16.0         230      5850   male 2009
260    Gentoo Biscoe     53.4     15.8         219      5500   male 2009
234    Gentoo Biscoe     52.5     15.6         221      5450   male 2009
244    Gentoo Biscoe     52.2     17.1         228      5400   male 2009
332 Chinstrap  Dream     52.2     18.8         197      3450   male 2009
242    Gentoo Biscoe     52.1     17.0         230      5550   male 2009
337 Chinstrap  Dream     51.9     19.5         206      3950   male 2009
266    Gentoo Biscoe     51.5     16.3         230      5500   male 2009
325 Chinstrap  Dream     51.5     18.7         187      3250   male 2009
328 Chinstrap  Dream     51.4     19.0         201      3950   male 2009
240    Gentoo Biscoe     51.3     14.2         218      5300   male 2009
252    Gentoo Biscoe     51.1     16.5         225      5250   male 2009
321 Chinstrap  Dream     50.9     17.9         196      3675 female 2009
238    Gentoo Biscoe     50.8     17.3         228      5600   male 2009
248    Gentoo Biscoe     50.8     15.7         226      5200   male 2009
322 Chinstrap  Dream     50.8     18.5         201      4450   male 2009
343 Chinstrap  Dream     50.8     19.0         210      4100   male 2009
330 Chinstrap  Dream     50.7     19.7         203      4050   male 2009
263    Gentoo Biscoe     50.5     15.2         216      5000 female 2009
274    Gentoo Biscoe     50.4     15.7         222      5750   male 2009
335 Chinstrap  Dream     50.2     18.8         202      3800   male 2009
344 Chinstrap  Dream     50.2     18.7         198      3775 female 2009
323 Chinstrap  Dream     50.1     17.9         190      3400 female 2009
 [ reached 'max' / getOption("max.print") -- omitted 319 rows ]</code></pre>
</div>
</div>
<p>Son satır işlemi olarak da unique olan değerleri seçmeyi - silmeyi göreceğiz. Verimiz bunun için yeterince uygun değil ama bir uygulama yapalım. Eğer bir data.frame’de tekrar eden değerlerle ya da eşsiz değerlerle bir filtreleme yapmak istiyorsanız mantıksal bir değer dönen <code>duplicated()</code> fonksiyonunu kullanabilirsiniz.</p>
<p>Mesela verimizi (data.frame), yalnızca eşsiz olan vücut kütlesi değerleri döndürmek istiyorsak aşağıdaki gibi filtreleyebiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[<span class="sc">!</span><span class="fu">duplicated</span>(peng_relocate<span class="sc">$</span>body_mass), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species    island bill_len bill_dep flipper_len body_mass    sex year
1   Adelie Torgersen     39.1     18.7         181      3750   male 2007
2   Adelie Torgersen     39.5     17.4         186      3800 female 2007
3   Adelie Torgersen     40.3     18.0         195      3250 female 2007
4   Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007
5   Adelie Torgersen     36.7     19.3         193      3450 female 2007
6   Adelie Torgersen     39.3     20.6         190      3650   male 2007
7   Adelie Torgersen     38.9     17.8         181      3625 female 2007
8   Adelie Torgersen     39.2     19.6         195      4675   male 2007
9   Adelie Torgersen     34.1     18.1         193      3475   &lt;NA&gt; 2007
10  Adelie Torgersen     42.0     20.2         190      4250   &lt;NA&gt; 2007
11  Adelie Torgersen     37.8     17.1         186      3300   &lt;NA&gt; 2007
12  Adelie Torgersen     37.8     17.3         180      3700   &lt;NA&gt; 2007
13  Adelie Torgersen     41.1     17.6         182      3200 female 2007
15  Adelie Torgersen     34.6     21.1         198      4400   male 2007
18  Adelie Torgersen     42.5     20.7         197      4500   male 2007
19  Adelie Torgersen     34.4     18.4         184      3325 female 2007
20  Adelie Torgersen     46.0     21.5         194      4200   male 2007
21  Adelie    Biscoe     37.8     18.3         174      3400 female 2007
22  Adelie    Biscoe     37.7     18.7         180      3600   male 2007
24  Adelie    Biscoe     38.2     18.1         185      3950   male 2007
27  Adelie    Biscoe     40.6     18.6         183      3550   male 2007
29  Adelie    Biscoe     37.9     18.6         172      3150 female 2007
32  Adelie     Dream     37.2     18.1         178      3900   male 2007
36  Adelie     Dream     39.2     21.1         196      4150   male 2007
40  Adelie     Dream     39.8     19.1         184      4650   male 2007
 [ reached 'max' / getOption("max.print") -- omitted 70 rows ]</code></pre>
</div>
</div>
<p>Tekrar eden değerleri döndürmek istediğimizde de <code>!</code> operatörü kullanmadan yapabiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>peng_relocate[<span class="fu">duplicated</span>(peng_relocate<span class="sc">$</span>body_mass), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   species    island bill_len bill_dep flipper_len body_mass    sex year
14  Adelie Torgersen     38.6     21.2         191      3800   male 2007
16  Adelie Torgersen     36.6     17.8         185      3700 female 2007
17  Adelie Torgersen     38.7     19.0         195      3450 female 2007
23  Adelie    Biscoe     35.9     19.2         189      3800 female 2007
25  Adelie    Biscoe     38.8     17.2         180      3800   male 2007
26  Adelie    Biscoe     35.3     18.9         187      3800 female 2007
28  Adelie    Biscoe     40.5     17.9         187      3200 female 2007
30  Adelie    Biscoe     40.5     18.9         180      3950   male 2007
31  Adelie     Dream     39.5     16.7         178      3250 female 2007
33  Adelie     Dream     39.5     17.8         188      3300 female 2007
34  Adelie     Dream     40.9     18.9         184      3900   male 2007
35  Adelie     Dream     36.4     17.0         195      3325 female 2007
37  Adelie     Dream     38.8     20.0         190      3950   male 2007
38  Adelie     Dream     42.2     18.5         180      3550 female 2007
39  Adelie     Dream     37.6     19.3         181      3300 female 2007
41  Adelie     Dream     36.5     18.0         182      3150 female 2007
42  Adelie     Dream     40.8     18.4         195      3900   male 2007
44  Adelie     Dream     44.1     19.7         196      4400   male 2007
49  Adelie     Dream     36.0     17.9         190      3450 female 2007
50  Adelie     Dream     42.3     21.2         191      4150   male 2007
53  Adelie    Biscoe     35.0     17.9         190      3450 female 2008
56  Adelie    Biscoe     41.4     18.6         191      3700   male 2008
57  Adelie    Biscoe     39.0     17.5         186      3550 female 2008
58  Adelie    Biscoe     40.6     18.8         193      3800   male 2008
60  Adelie    Biscoe     37.6     19.1         194      3750   male 2008
 [ reached 'max' / getOption("max.print") -- omitted 224 rows ]</code></pre>
</div>
</div>
</section>
<section id="grup-işlemleri" class="level3">
<h3 class="anchored" data-anchor-id="grup-işlemleri">GRUP İŞLEMLERİ</h3>
<p>Eğer <code>dplyr</code> fonksiyonlarına aşinaysanız <code>group_by() |&gt; summarise()</code> ikilisini mutlaka biliyorsunuzdur. Özet istatistik tabloları oluşturmak için oldukça kullanışlı bir yöntem. <code>base R</code>’da da bunu <code>tapply()</code>, <code>aggregate()</code> ya da <code>by()</code> fonksiyonuyla yapabilirsiniz. Eğer <code>dplyr</code>’deki <code>group_by() |&gt; mutate()</code> ikilisini base R ile yapmak istiyorsanız da <code>ave()</code> fonsiyonu güzel bir alternatif olabilir. <code>base R</code> basit gruplama + özetleme işlemleri için <code>dplyr</code>’a göre daha sezgisel, daha kolay ancak birden fazla fonksiyon kullanarak yapacağımız ve bir data.frame dönmesini istediğimiz işlerde <code>dplyr</code>’ı daha kullanışlı buluyorum. Neyse bu yazının konusu base R - tidyverse karşılaştırması değil. Bu konuda <code>dplyr</code> ve <code>base R</code>’a eşit oranda aşina olmayanlar için Excel’deki (kendilerini hiç sevmem :)) pivot table’a oldukça benzediğini söyleyebilirim. Özetle bir gruba göre özet istatistik tablosu oluşturacaksak yukarıda bahsettiğim fonksiyonlar tam da bu iş için.</p>
<p>Basit bir örnekle başlayalım. Diyelim ki ortalama bill_len’i hesaplamak istiyoruz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(peng_relocate<span class="sc">$</span>bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># na.rm = TRUE kullanarak ortalama hesaplarken NA degerleri yok sayiyoruz.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43.92193</code></pre>
</div>
</div>
<p>Bunun için <code>mean()</code> fonksiyonunu kullanmamız yeterli.</p>
<p>Ancak her bir grubun ortalamasını hesaplamak istiyorsak bunun için en iyi yöntem <code>tapply()</code> fonksiyonunu kullanmaktır. Son derece sezgisel, kolay bir fonksiyon. Daha önce <code>lapply()</code>, <code>sapply()</code> ya da <code>apply()</code> fonksiyonunu duymuş olabilirsiniz. R’da fonksiyonel programlama yaklaşımıyla, loop yazmadan tekrarlayan işleri yapmamıza yarayan <code>apply</code> ailesi fonksiyonları bunlar. <code>tapply()</code>’de bunlardan birisi.</p>
<p>Her bir tür için ortamala gaga uzunluğunu öğrenmek istediğimizi varsayalım. İlk argüman olarak özetlemeyi istediğimiz değişkeni yazıyoruz. İkinci argüman olarak grupladığımız değişkeni ve üçüncü olarak da fonksiyonu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(peng_relocate<span class="sc">$</span>bill_len, peng_relocate<span class="sc">$</span>species, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Adelie Chinstrap    Gentoo 
 38.79139  48.83382  47.50488 </code></pre>
</div>
</div>
<p>Burada <code>na.rm</code> argümanı kafanızı karıştırmasın diye aşağıdaki şekillerde de yazabiliriz bu fonksiyonu. Son argümanı fonksiyon içinde gösteriyoruz. Bu da daha okunaklı oluyor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(peng_relocate<span class="sc">$</span>bill_len, peng_relocate<span class="sc">$</span>species, <span class="cf">function</span>(x) <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Adelie Chinstrap    Gentoo 
 38.79139  48.83382  47.50488 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(peng_relocate<span class="sc">$</span>bill_len, peng_relocate<span class="sc">$</span>species, \(x) <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Adelie Chinstrap    Gentoo 
 38.79139  48.83382  47.50488 </code></pre>
</div>
</div>
<p><code>\()</code> anonymous function diye geçen bir fonksiyon. Daha önce görmemiş olabilirsiniz. R’ın 4.1.0 versiyonuyla beraber, native pipe (<code>|&gt;</code>) ile birlikte gelen bir özellik. Tek satırlık bir fonksiyonunuz varsa <code>function(x)</code> yerine <code>\(x)</code> kullanabilirsiniz. Aynı işlevi görüyor.</p>
<p>Diyelim ki hem ada hem de türler için ortalama hesaplamak istiyoruz. O zaman grup değişkenlerini bir <code>list()</code> ile vermemiz gerekiyor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  peng_relocate<span class="sc">$</span>bill_len, </span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(peng_relocate<span class="sc">$</span>species, peng_relocate<span class="sc">$</span>island), </span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>  \(x) <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Biscoe    Dream Torgersen
Adelie    38.97500 38.50179  38.95098
Chinstrap       NA 48.83382        NA
Gentoo    47.50488       NA        NA</code></pre>
</div>
</div>
<p>Eğer tek bir gruba ve birden çok fonksiyona göre özet istatistik çıkartacaksanız aşağıdaki gibi bir data.frame içerisinde tanımlayabilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  peng_relocate<span class="sc">$</span>bill_len, </span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>  peng_relocate<span class="sc">$</span>species, </span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>  \(x) <span class="fu">data.frame</span>(</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Adelie
      mean median
1 38.79139   38.8

$Chinstrap
      mean median
1 48.83382  49.55

$Gentoo
      mean median
1 47.50488   47.3</code></pre>
</div>
</div>
<p>Ancak birden fazla grup için birden fazla özet istatistik hesaplamak istiyorsanız <code>aggregate()</code> ya da <code>by()</code> fonksiyonunu kullanmanızı öneririm. <code>tapply()</code> bu durumda karmaşık hâle gelebilir. Ya da en azından ben basit yolunu bulamamışımdır. Basit bir yolunu bilen varsa yorumlarda belirtsin lütfen. :)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>  peng_relocate<span class="sc">$</span>bill_len, </span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(peng_relocate<span class="sc">$</span>species, peng_relocate<span class="sc">$</span>island), </span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>  \(x) <span class="fu">c</span>(</span>
<span id="cb132-5"><a href="#cb132-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb132-6"><a href="#cb132-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb132-7"><a href="#cb132-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb132-8"><a href="#cb132-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Group.1   Group.2   x.mean x.median
1    Adelie    Biscoe 38.97500 38.70000
2    Gentoo    Biscoe 47.50488 47.30000
3    Adelie     Dream 38.50179 38.55000
4 Chinstrap     Dream 48.83382 49.55000
5    Adelie Torgersen 38.95098 38.90000</code></pre>
</div>
</div>
<p>Ya da karmaşık işlerde en kullanışlı olan <code>by()</code> fonksiyonu. Aslında her üç fonksiyonun da argüman sırası benzer. Bu açıdan çok avantajlı. Sadece kullanımda bazı farklılıklar var. <code>by()</code> kullanırken eğer özet tabloda grup değerlerini de görmek istiyorsak -ki bence önemli- aşağıdaki gibi <code>x$species[1]</code> şeklinde göstermeliyiz. Bu, her bir tekrarda yalnızca ilk değeri alacaktır. Ardından da <code>list()</code> benzeri bir veri döndürecektir. Eğer bu veriyi data.frame’e döndürmek istiyorsak <code>do.call()</code> fonksiyonu içinde <code>rbind()</code> kullanmamız gerekiyor. Biliyorum başta oldukça karmaşık geliyor ama zamanla o kadar da zor olmadığı anlaşılıyor. Bir fonksiyonu, argümanlarını list’ten alacak şekilde çağırmak istediğimiz her zaman <code>do.call()</code> kullanmak zorundayız. :) <code>lapply()</code> fonksiyonunu kullandığınızda -R’daki en önemli fonksiyonlardan birisi kesinlikle- <code>do.call()</code> fonksiyonunu da bolca kullanacaksınız. Zamanla oturacaktır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>dat_by <span class="ot">&lt;-</span> <span class="fu">by</span>(</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>  peng_relocate, </span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(peng_relocate<span class="sc">$</span>species, peng_relocate<span class="sc">$</span>island), </span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a>  \(x) <span class="fu">data.frame</span>(</span>
<span id="cb134-5"><a href="#cb134-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">species =</span> x<span class="sc">$</span>species[<span class="dv">1</span>], <span class="co"># sadece essiz degerleri almasi icin</span></span>
<span id="cb134-6"><a href="#cb134-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">island =</span> x<span class="sc">$</span>island[<span class="dv">1</span>],   <span class="co"># sadece essiz degerleri almasi icin</span></span>
<span id="cb134-7"><a href="#cb134-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(x<span class="sc">$</span>bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb134-8"><a href="#cb134-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(x<span class="sc">$</span>bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb134-9"><a href="#cb134-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb134-10"><a href="#cb134-10" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb134-11"><a href="#cb134-11" aria-hidden="true" tabindex="-1"></a>peng_summ <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, dat_by)</span>
<span id="cb134-12"><a href="#cb134-12" aria-hidden="true" tabindex="-1"></a>peng_summ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    species    island     mean median
1    Adelie    Biscoe 38.97500  38.70
2    Gentoo    Biscoe 47.50488  47.30
3    Adelie     Dream 38.50179  38.55
4 Chinstrap     Dream 48.83382  49.55
5    Adelie Torgersen 38.95098  38.90</code></pre>
</div>
</div>
<p>Temiz iş akışı, temiz sonuç! <code>dplyr</code> paketindeki <code>group_by() |&gt; summarise()</code> ikilisine oldukça güçlü bir alternatif. Hem de <code>base R</code> sağlamlığıyla.</p>
<p>Son söz olarak tek fonksiyonlu özetler için <code>tapply()</code> ve <code>aggregate()</code>, çok fonksiyonlular için ise yine <code>aggregate()</code> ve özellikle de <code>by()</code> oldukça güçlü fonksiyonlar.</p>
</section>
</section>
<section id="biraz-da-grafik" class="level2">
<h2 class="anchored" data-anchor-id="biraz-da-grafik">3. BİRAZ DA GRAFİK</h2>
<p>Birçok temel şey gördüğümüze göre şimdi verimizi görselleştirmeye başlayabiliriz. En heyecanlı kısımlardan birisi bu çünkü emeğinizin karşılığını aldığınızı somut bir göstergesi.</p>
<p>Bu yazıda yalnızca <code>base R</code> ile gelen <code>plot()</code> fonksiyonu ve onun kardeşlerini kullanacağız. Basit grafikler çizmek için çok kolay ve hızlı bir yol. İleride <code>ggplot2</code> gibi bir kütüphane kullansanız bile analiz esnasında veriyi hızlıca görmek için kullanabileceğiniz bir fonksiyon. Aslında birçok modern R kullanıcısı base R grafiklerini küçümseme eğiliminde çünkü <code>ggplot2</code> muhteşem bir paket ve karmaşık grafikler yapmak için eşsiz bir araç sunuyor ancak base R da düşünüldüğü gibi basit olmayan, aslında daha esnek ve istenildiği zaman çok farklı ve kompleks grafikler çizmeye olanak sağlayabiliyor. Meraklıları şu bağlantıları ziyaret edebilir:</p>
<ol type="1">
<li><a href="https://github.com/karoliskoncevicius/r_notes/blob/main/baseplotting.md">https://github.com/karoliskoncevicius/r_notes/blob/main/baseplotting.md</a></li>
<li><a href="https://poisonalien.github.io/basegraphics/baseplots.html">https://poisonalien.github.io/basegraphics/baseplots.html</a></li>
<li><a href="https://plantarum.ca/2014/02/19/r-graphics/">https://plantarum.ca/2014/02/19/r-graphics/</a></li>
<li><a href="https://plantarum.ca/2023/02/13/terra-maps/">https://plantarum.ca/2023/02/13/terra-maps/</a></li>
</ol>
<p>Biz tabi burada daha basit grafikler çizeceğiz. :)</p>
<p>Öncelikle <code>plot()</code> fonksiyonu ile bir data.frame’i direkt çizmek istersek tüm sütunları ve birbirleriyle ilişkisini çizecektir. Bu da 8x8’lik bir matrix demek.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Oldukça karmaşık görünüyor değil mi? Bu gibi grafikleri kullandığımız zamanlar olabiliyor ama şu an hiç mi hiç gerek yok.</p>
<p>Öncelikle çizmek istediğimiz sütunları seçerek başlayalım, ilk sıraya x ekseninde istediğimiz değişkeni, ikinci sırada da y ekseninde istediğimiz değişkeni yazacağız.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(penguins<span class="sc">$</span>flipper_len, penguins<span class="sc">$</span>bill_len)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Şimdi de <code>pch = 16</code> ile nokta şeklini belirleyelim. <a href="https://r-charts.com/base-r/pch-symbols/">Şuradan</a> şekil kodlarına ilişkin daha fazla bilgi edinebilirsiniz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(penguins<span class="sc">$</span>flipper_len, penguins<span class="sc">$</span>bill_len, <span class="at">pch =</span> <span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Eksen başlıklarını değiştirelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>flipper_len, </span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>bill_len, </span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb139-5"><a href="#cb139-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Flipper Length [mm]"</span>,</span>
<span id="cb139-6"><a href="#cb139-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Bill Length [mm]"</span></span>
<span id="cb139-7"><a href="#cb139-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-68-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Noktaların rengini kırmızı yapalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>flipper_len, </span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>bill_len, </span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"red"</span>,</span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb140-6"><a href="#cb140-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Flipper Length [mm]"</span>,</span>
<span id="cb140-7"><a href="#cb140-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Bill Length [mm]"</span></span>
<span id="cb140-8"><a href="#cb140-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Şimdi de renkleri <code>species</code> değişkenine göre belirleyelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>flipper_len, </span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>bill_len, </span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> penguins<span class="sc">$</span>species,</span>
<span id="cb141-5"><a href="#cb141-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb141-6"><a href="#cb141-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Flipper Length [mm]"</span>,</span>
<span id="cb141-7"><a href="#cb141-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Bill Length [mm]"</span></span>
<span id="cb141-8"><a href="#cb141-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-70-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Bir de lejant ekleyelim. Base R plot fonksiyonunun en büyük dezavantajlarından birisi lejantı manuel olarak çizmeniz gerekmesi. Bu konuda <a href="https://grantmcdermott.com/tinyplot/">tinyplot</a> paketine bakabilirsiniz. <code>tinyplot</code>, base graphics üzerine otomatik lejant gibi birçok kullanışlı özellik ekleyen, daha modern, daha basit ve sıfır bağımlılıklı bir paket. Bakmanızı mutlaka öneririm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>flipper_len, </span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>bill_len, </span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> penguins<span class="sc">$</span>species,</span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb142-6"><a href="#cb142-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Flipper Length [mm]"</span>,</span>
<span id="cb142-7"><a href="#cb142-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Bill Length [mm]"</span></span>
<span id="cb142-8"><a href="#cb142-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb142-9"><a href="#cb142-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">levels</span>(penguins<span class="sc">$</span>species), <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">title =</span> <span class="st">"Species"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Burada da nokta şekillerini de <code>species</code> değişkenine göre değiştiriyoruz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>flipper_len, </span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>bill_len, </span>
<span id="cb143-4"><a href="#cb143-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> penguins<span class="sc">$</span>species,</span>
<span id="cb143-5"><a href="#cb143-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="fu">as.integer</span>(penguins<span class="sc">$</span>species),</span>
<span id="cb143-6"><a href="#cb143-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Flipper Length [mm]"</span>,</span>
<span id="cb143-7"><a href="#cb143-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Bill Length [mm]"</span></span>
<span id="cb143-8"><a href="#cb143-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb143-9"><a href="#cb143-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb143-10"><a href="#cb143-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"topright"</span>, </span>
<span id="cb143-11"><a href="#cb143-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="fu">levels</span>(penguins<span class="sc">$</span>species),</span>
<span id="cb143-12"><a href="#cb143-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb143-13"><a href="#cb143-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="fu">unique</span>(<span class="fu">as.integer</span>(penguins<span class="sc">$</span>species)), </span>
<span id="cb143-14"><a href="#cb143-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Species"</span></span>
<span id="cb143-15"><a href="#cb143-15" aria-hidden="true" tabindex="-1"></a> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-72-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Son olarak da basit bir histogram çizip, verimizin dağılımına bakalım.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(penguins<span class="sc">$</span>bill_dep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-74-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>  penguins<span class="sc">$</span>bill_dep, </span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Bill Depth [mm]"</span>, </span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Histogram of Bill Depth"</span></span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="penguins_files/figure-html/unnamed-chunk-75-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fazlasıyla uzun bir yazı oldu. Umarım okucuyular için faydalı olur. En ufak bir sorunuz bile olsa lütfen sormaktan çekinmeyin.</p>
<p>Bilimle ve huzurla kalınız!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="R-delisi/r-delisi.github.io" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>R DELİSİ - 2026</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>