project:
  type: website
  output-dir: docs

website:
  title: "R Delisi"
  description: "Açık ve Tekrarlanabilir Bilim"
  favicon: "favicon.jpeg"
  navbar:
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: true
    left:
      - href: index.qmd
        text: Blog
      - about.qmd
    right:
      - icon: 'mastodon'
        href: 'https://ecoevo.social/@mehmet_goktu'
      - icon: 'twitter'
        href: "https://twitter.com/mehmet_goktu"
      - icon: 'github'
        href: "https://github.com/mehmetgoktug"
      - icon: 'linkedin'
        href: "https://www.linkedin.com/in/mehmetgoktug/"
  page-footer: 
    center: R Delisi - 2023
  twitter-card:
    creator: "@mehmet_goktu"
    site: "@mehmet_goktu"
  open-graph:
    locale: tr_TR
  comments:
    utterances:
      repo: 'R-delisi/r-delisi.github.io'

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: Inconsolata
    fontsize: 1rem
    css: styles.css
    toc: true



