project:
  type: website
  output-dir: docs

lang: tr
date-format: "D MMM YYYY"

website:
  title: "R DELİSİ"
  description: "Açık ve Tekrarlanabilir Bilim"
  favicon: "favicon.webp"
  search: false
  comments:
    utterances:
      repo: 'R-delisi/r-delisi.github.io'

format:
  html:
    theme: none
    fontsize: 1.1rem
    include-in-header: 
      - header.html
    include-before-body: 
      - _includes/site-header.html
    toc: true
    toc-title: ""
    html-math-method: plain
    css: styles.css
    anchor-sections: false
    citations-hover: false
    smooth-scroll: false
    footnotes-hover: false
    crossrefs-hover: false
    code-copy: true


