project:
  type: website
  output-dir: docs

website:
  title: "R Delisi"
  navbar:
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: true
    left:
      - href: index.qmd
        text: Blog
      - about.qmd
    right:
      - icon: 'mastodon'
        href: 'https://ecoevo.social/@mehmet_goktu'
      - icon: 'twitter'
        href: "https://twitter.com/mehmet_goktu"
      - icon: 'github'
        href: "https://github.com/mehmetgoktug"
      - icon: 'linkedin'
        href: "https://www.linkedin.com/in/mehmetgoktug/"
  twitter-card:
    creator: "@mehmet_goktu"
    site: "@mehmet_goktu"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    highlight-style: nord



